/**
 * Create, manage, and chat with agent sessions
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';
import { streamSSE } from '../streaming.js';

export class AgentsSessionsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Sessions
 *
 * @param agentId - The agent_id parameter
 * @param offset - Number of items to skip
 * @param limit - Maximum number of items to return
 * @param sortBy - Field to sort by: start_time, status
 * @param sortOrder - Sort order: asc or desc
 * @param status - Filter by execution status: RUNNING, COMPLETED, FAILED, CANCELED, TERMINATED
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listSessions(agentId: string, options?: { offset?: number; limit?: number | null; sortBy?: string; sortOrder?: string; status?: string | null }): AsyncIterable<models.SessionSummary> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
      sort_by: options?.sortBy ?? undefined,
      sort_order: options?.sortOrder ?? undefined,
      status: options?.status ?? undefined,
    };

    yield* paginate<models.SessionSummary>(async (cursor) => {
      const response = await this.http.request<models.SessionListResponse>(`/agents/${agentId}/sessions`, {
        method: "GET",
        params: {
          ...queryParams,
          offset: cursor,
        },
      });
      return {
        items: response.data ?? [],
      };
    });
  }

/**
 * Create Session
 *
 * @param agentId - The agent_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async createSession(agentId: string, body?: models.CreateSessionRequest | null): Promise<models.CreateSessionResponse> {
    const response = await this.http.request<models.CreateSessionResponse>(`/agents/${agentId}/sessions`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Send Chat Message
 *
 * @param sessionId - The session_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async sendChatMessage(sessionId: string, body: models.ChatMessageRequest): Promise<models.ChatMessageResponse> {
    const response = await this.http.request<models.ChatMessageResponse>(`/sessions/${sessionId}/chat`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Send a chat message and stream the response via SSE
 *
 * @param sessionId - The session_id parameter
 * @param body - Request body
 *
 * @throws {ApiError} If the request fails
 */
  async *sendChatMessageStream(sessionId: string, body: models.ChatMessageRequest): AsyncIterable<Record<string, unknown>> {
    const response = await this.http.request<Response>(`/sessions/${sessionId}/chat/stream`, {
      method: "POST",
      body,
      stream: true,
    });

    yield* streamSSE(response);
  }

}
