/**
 * Create, manage, and publish AI agents
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';

export class AgentsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Agents
 *
 * @param offset - Number of items to skip
 * @param limit - Maximum number of items to return
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listAgents(options?: { offset?: number; limit?: number | null }): AsyncIterable<models.AgentSummary> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
    };

    yield* paginate<models.AgentSummary>(async (cursor) => {
      const response = await this.http.request<models.AgentListResponse>("/agents/", {
        method: "GET",
        params: {
          ...queryParams,
          offset: cursor,
        },
      });
      return {
        items: response.data ?? [],
      };
    });
  }

/**
 * Create Agent
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async createAgent(body: models.CreateAgentDefinitionRequest): Promise<models.CreateAgentResponse> {
    const response = await this.http.request<models.CreateAgentResponse>("/agents/", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Agent
 *
 * @param agentId - The agent_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getAgent(agentId: string): Promise<models.AgentDetailResponse> {
    const response = await this.http.request<models.AgentDetailResponse>(`/agents/${agentId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Agent
 *
 * @param agentId - The agent_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateAgent(agentId: string, body: models.UpdateAgentDefinitionRequest): Promise<models.UpdateAgentDefinitionResponse> {
    const response = await this.http.request<models.UpdateAgentDefinitionResponse>(`/agents/${agentId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Agent
 *
 * @param agentId - The agent_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async deleteAgent(agentId: string): Promise<void> {
    const response = await this.http.request<void>(`/agents/${agentId}`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Publish Agent
 *
 * @param agentId - The agent_id parameter
 * @param overrideDraft - Bypass draft head validation and publish any version directly
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async publishAgent(agentId: string, body: models.PublishAgentDefinitionRequest, options?: { overrideDraft?: boolean }): Promise<models.PublishAgentDefinitionResponse> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      override_draft: options?.overrideDraft ?? undefined,
    };

    const response = await this.http.request<models.PublishAgentDefinitionResponse>(`/agents/${agentId}/publish`, {
      method: "POST",
      params: queryParams,
      body,
    });

    return response;
  }

/**
 * List Agent Versions
 *
 * @param agentId - The agent_id parameter
 * @param published - If true, return only published versions. If omitted, return all versions.
 * @param offset - Number of items to skip
 * @param limit - Maximum number of items to return
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listAgentVersions(agentId: string, options?: { published?: boolean | null; offset?: number; limit?: number | null }): AsyncIterable<models.AgentVersionSummary> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      published: options?.published ?? undefined,
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
    };

    yield* paginate<models.AgentVersionSummary>(async (cursor) => {
      const response = await this.http.request<models.AgentVersionListResponse>(`/agents/${agentId}/versions`, {
        method: "GET",
        params: {
          ...queryParams,
          offset: cursor,
        },
      });
      return {
        items: response.data ?? [],
      };
    });
  }

/**
 * List Sessions
 *
 * @param agentId - The agent_id parameter
 * @param offset - Number of items to skip
 * @param limit - Maximum number of items to return
 * @param sortBy - Field to sort by: start_time, status
 * @param sortOrder - Sort order: asc or desc
 * @param status - Filter by execution status: RUNNING, COMPLETED, FAILED, CANCELED, TERMINATED
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listSessions(agentId: string, options?: { offset?: number; limit?: number | null; sortBy?: string; sortOrder?: string; status?: string | null }): AsyncIterable<models.SessionSummary> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
      sort_by: options?.sortBy ?? undefined,
      sort_order: options?.sortOrder ?? undefined,
      status: options?.status ?? undefined,
    };

    yield* paginate<models.SessionSummary>(async (cursor) => {
      const response = await this.http.request<models.SessionListResponse>(`/agents/${agentId}/sessions`, {
        method: "GET",
        params: {
          ...queryParams,
          offset: cursor,
        },
      });
      return {
        items: response.data ?? [],
      };
    });
  }

/**
 * Create Session
 *
 * @param agentId - The agent_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async createSession(agentId: string, body?: models.CreateSessionRequest | null): Promise<models.CreateSessionResponse> {
    const response = await this.http.request<models.CreateSessionResponse>(`/agents/${agentId}/sessions`, {
      method: "POST",
      body,
    });

    return response;
  }

}
