/**
 * Create, manage, and chat with agent sessions
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';
import { streamSSE } from '../streaming.js';
import type { UploadFile } from '../upload.js';

export class AgentsSessionsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Sessions
 *
 * @param agentId - The agent_id parameter
 * @param offset - Number of items to skip
 * @param limit - Maximum number of items to return
 * @param sortBy - Field to sort by: start_time, status
 * @param sortOrder - Sort order: asc or desc
 * @param status - Filter by execution status: RUNNING, COMPLETED, FAILED, CANCELED, TERMINATED
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listSessions(agentId: string, options?: { offset?: number; limit?: number | null; sortBy?: string; sortOrder?: string; status?: string | null }): AsyncIterable<models.SessionSummary> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
      sort_by: options?.sortBy ?? undefined,
      sort_order: options?.sortOrder ?? undefined,
      status: options?.status ?? undefined,
    };

    yield* paginate<models.SessionSummary>(async (cursor) => {
      const response = await this.http.request<models.SessionListResponse>(`/agents/${agentId}/sessions`, {
        method: "GET",
        params: {
          ...queryParams,
          offset: cursor,
        },
      });
      return {
        items: response.data ?? [],
      };
    });
  }

/**
 * Create Session
 *
 * @param agentId - The agent_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async createSession(agentId: string, body?: models.CreateSessionRequest | null): Promise<models.CreateSessionResponse> {
    const response = await this.http.request<models.CreateSessionResponse>(`/agents/${agentId}/sessions`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Send Chat Message
 *
 * @param sessionId - The session_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async sendChatMessage(sessionId: string, body: models.ChatMessageRequest): Promise<models.ChatMessageResponse> {
    const response = await this.http.request<models.ChatMessageResponse>(`/sessions/${sessionId}/chat`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Send a chat message with file attachments and stream the response via SSE
 *
 * @param sessionId - The session_id parameter
 * @param body - Request body
 *
 * @throws {ApiError} If the request fails
 */
  async *sendChatMessageStream(sessionId: string, files?: ReadableStream<Uint8Array> | Blob | File, filesName?: string, options?: { userMessage?: string | null; timeoutSeconds?: number | null; includeThinking?: boolean | null; includeToolActivity?: boolean | null }): AsyncIterable<models.ConnectedEvent | models.StatusEvent | models.ToolCallEvent | models.ToolResultEvent | models.PartialResponseEvent | models.CompletionEvent | models.ErrorEvent> {
    const path = `/sessions/${sessionId}/chat/stream`;
    const formFields: Record<string, string> = {};
    if (options?.userMessage !== undefined) {
      formFields['user_message'] = String(options.userMessage);
    }
    if (options?.timeoutSeconds !== undefined) {
      formFields['timeout_seconds'] = String(options.timeoutSeconds);
    }
    if (options?.includeThinking !== undefined) {
      formFields['include_thinking'] = String(options.includeThinking);
    }
    if (options?.includeToolActivity !== undefined) {
      formFields['include_tool_activity'] = String(options.includeToolActivity);
    }
    if (files) {
      const response = await this.http.upload<Response>(path, [
        { fieldName: 'files', fileName: filesName ?? 'file', content: files },
      ], { formFields, stream: true });
      yield* streamSSE(response);
    } else {
      const response = await this.http.request<Response>(path, {
        method: "POST",
        formData: formFields,
        stream: true,
      });
      yield* streamSSE(response);
    }
  }

}
