/**
 * Define structured output schemas for agent artifacts
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';
import { z } from 'zod';
import { zodToJsonSchema } from '../schema.js';

export class ArtifactSchemasResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Artifact Schemas
 *
 * @param offset - Number of items to skip
 * @param limit - Maximum number of items to return
 * @param sortBy - Field to sort by: created_at, name, display_name
 * @param sortOrder - Sort order: asc or desc
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *list(options?: { offset?: number; limit?: number | null; sortBy?: string | null; sortOrder?: string | null }): AsyncIterable<models.ArtifactSchemaSummary> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
      sort_by: options?.sortBy ?? undefined,
      sort_order: options?.sortOrder ?? undefined,
    };

    yield* paginate<models.ArtifactSchemaSummary>(async (cursor) => {
      const response = await this.http.request<models.ArtifactSchemaListResponse>("/artifact-schemas/", {
        method: "GET",
        params: {
          ...queryParams,
          offset: cursor,
        },
      });
      return {
        items: response.data ?? [],
      };
    });
  }

/**
 * Create Artifact Schema
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async create(options: { displayName: string; type?: models.ArtifactType; description?: string | null; required?: boolean | null; schema: string | Record<string, unknown> | z.ZodType; maxSizeBytes?: number | null; storageStrategy?: models.ArtifactStorageStrategy | null; additionalProperties?: Record<string, unknown> }): Promise<models.CreateArtifactSchemaResponse> {
    const _schema = options.schema instanceof z.ZodType
      ? zodToJsonSchema(options.schema)
      : options.schema;
    const body = {
      display_name: options.displayName,
      type: options.type,
      description: options.description,
      required: options.required,
      schema_def: _schema,
      max_size_bytes: options.maxSizeBytes,
      storage_strategy: options.storageStrategy,
      additional_properties: options.additionalProperties,
    };

    const response = await this.http.request<models.CreateArtifactSchemaResponse>("/artifact-schemas/", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Artifact Schema
 *
 * @param artifactId - The artifact_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async get(artifactId: string): Promise<models.ArtifactSchemaResponse> {
    const response = await this.http.request<models.ArtifactSchemaResponse>(`/artifact-schemas/${artifactId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Artifact Schema
 *
 * @param artifactId - The artifact_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async update(artifactId: string, body: models.UpdateAgentArtifactRequest): Promise<models.UpdateArtifactSchemaResponse> {
    const response = await this.http.request<models.UpdateArtifactSchemaResponse>(`/artifact-schemas/${artifactId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Artifact Schema
 *
 * @param artifactId - The artifact_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async delete(artifactId: string): Promise<void> {
    const response = await this.http.request<void>(`/artifact-schemas/${artifactId}`, {
      method: "DELETE",
    });

    return response;
  }

}
