/**
 * Run, monitor, and manage batch executions
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';

export class BatchExecutionsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Batch Executions
 *
 * @param inputDatasourceId - Filter by input datasource ID
 * @param offset - The offset parameter
 * @param limit - The limit parameter
 * @param sortBy - Field to sort by: start_time, status
 * @param sortOrder - The sort_order parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *list(options?: { inputDatasourceId?: string | null; offset?: number; limit?: number | null; sortBy?: string; sortOrder?: string }): AsyncIterable<models.BatchExecutionResponse> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      input_datasource_id: options?.inputDatasourceId ?? undefined,
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
      sort_by: options?.sortBy ?? undefined,
      sort_order: options?.sortOrder ?? undefined,
    };

    yield* paginate<models.BatchExecutionResponse>(async (cursor) => {
      const response = await this.http.request<models.GetBatchExecutionsResponse>("/batch-executions/", {
        method: "GET",
        params: {
          ...queryParams,
          offset: cursor,
        },
      });
      return {
        items: response.data ?? [],
      };
    });
  }

/**
 * Create Batch Execution
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async create(body: models.CreateBatchExecutionRequest): Promise<models.BatchExecutionResponse> {
    const response = await this.http.request<models.BatchExecutionResponse>("/batch-executions/", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Batch Execution By Id
 *
 * @param executionId - The execution_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getById(executionId: string): Promise<models.BatchExecutionResponse> {
    const response = await this.http.request<models.BatchExecutionResponse>(`/batch-executions/id/${executionId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Batch Execution By Id
 *
 * @param executionId - The execution_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateById(executionId: string, body: models.UpdateBatchExecutionRequest): Promise<models.BatchExecutionResponse> {
    const response = await this.http.request<models.BatchExecutionResponse>(`/batch-executions/id/${executionId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Get Batch Realtime Progress
 *
 * @param executionId - The execution_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getBatchRealtimeProgress(executionId: string): Promise<string> {
    const response = await this.http.request<string>(`/batch-executions/id/${executionId}/realtime-progress`, {
      method: "GET",
    });

    return response;
  }

/**
 * Retry Failed Items
 *
 * @param executionId - The execution_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async retryFailedItems(executionId: string): Promise<models.BatchExecutionResponse> {
    const response = await this.http.request<models.BatchExecutionResponse>(`/batch-executions/id/${executionId}/retry-failed`, {
      method: "POST",
    });

    return response;
  }

/**
 * Cancel Batch Execution
 *
 * @param executionId - The execution_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async cancel(executionId: string): Promise<models.BatchExecutionResponse> {
    const response = await this.http.request<models.BatchExecutionResponse>(`/batch-executions/id/${executionId}/cancel`, {
      method: "POST",
    });

    return response;
  }

}
