/**
 * Create and manage batch processing definitions
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { ExecutionsResource } from './executions.js';

export class BatchesResource {
  public readonly executions: ExecutionsResource;

  constructor(private readonly http: HttpClient) {
    this.executions = new ExecutionsResource(http);
  }

/**
 * List Batch Definitions
 *
 * @param offset - The offset parameter
 * @param limit - The limit parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async list(options?: { offset?: number; limit?: number }): Promise<models.GetBatchDefinitionsResponse> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
    };

    const response = await this.http.request<models.GetBatchDefinitionsResponse>("/batch-definitions/", {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * Create Batch Definition
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async create(body: models.CreateBatchDefinitionRequest): Promise<models.CreateBatchDefinitionResponse> {
    const response = await this.http.request<models.CreateBatchDefinitionResponse>("/batch-definitions/", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Batch Definition By Catalog Urn
 *
 * @param catalogUrn - urn:meibel:batch-definition:{customer}:{project}:{id}
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getByCatalogUrn(catalogUrn: string): Promise<models.BatchDefinitionResponse> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      catalog_urn: catalogUrn,
    };

    const response = await this.http.request<models.BatchDefinitionResponse>("/batch-definitions/catalog-urn", {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * Get Batch Definition By Id
 *
 * @param definitionId - The definition_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getById(definitionId: string): Promise<models.BatchDefinitionResponse> {
    const response = await this.http.request<models.BatchDefinitionResponse>(`/batch-definitions/id/${definitionId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Batch Definition By Id
 *
 * @param definitionId - The definition_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateById(definitionId: string, body: models.UpdateBatchDefinitionRequest): Promise<models.UpdateBatchDefinitionResponse> {
    const response = await this.http.request<models.UpdateBatchDefinitionResponse>(`/batch-definitions/id/${definitionId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Batch Definition By Id
 *
 * @param definitionId - The definition_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async deleteById(definitionId: string): Promise<void> {
    const response = await this.http.request<void>(`/batch-definitions/id/${definitionId}`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * List Batch Definition Versions
 *
 * @param definitionId - The definition_id parameter
 * @param offset - The offset parameter
 * @param limit - The limit parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async listVersions(definitionId: string, options?: { offset?: number; limit?: number | null }): Promise<models.GetBatchDefinitionsResponse> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
    };

    const response = await this.http.request<models.GetBatchDefinitionsResponse>(`/batch-definitions/id/${definitionId}/versions`, {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * Execute Batch Definition
 *
 * @param definitionId - The definition_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async execute(definitionId: string): Promise<models.ExecuteBatchDefinitionResponse> {
    const response = await this.http.request<models.ExecuteBatchDefinitionResponse>(`/batch-definitions/id/${definitionId}/execute`, {
      method: "POST",
    });

    return response;
  }

}
