/**
 * Blueprints resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { ExecutionsResource } from './executions.js';
import { InstancesResource } from './instances.js';

export class BlueprintsResource {
  public readonly executions: ExecutionsResource;
  public readonly instances: InstancesResource;

  constructor(private readonly http: HttpClient) {
    this.executions = new ExecutionsResource(http);
    this.instances = new InstancesResource(http);
  }

/**
 * Get Blueprints
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getBlueprints(): Promise<models.GetBlueprintsResponse> {
    const response = await this.http.request<models.GetBlueprintsResponse>("/blueprint/", {
      method: "GET",
    });

    return response;
  }

/**
 * Create Blueprint
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async createBlueprint(body: models.AddBlueprintRequest): Promise<models.AddBlueprintResponse> {
    const response = await this.http.request<models.AddBlueprintResponse>("/blueprint/", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Blueprint
 *
 * @param blueprintId - The blueprint_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getBlueprint(blueprintId: string): Promise<models.Blueprint> {
    const response = await this.http.request<models.Blueprint>(`/blueprint/${blueprintId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Blueprint
 *
 * @param blueprintId - The blueprint_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateBlueprint(blueprintId: string, body: models.UpdateBlueprintRequest): Promise<models.Blueprint> {
    const response = await this.http.request<models.Blueprint>(`/blueprint/${blueprintId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Blueprint
 *
 * @param blueprintId - The blueprint_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteBlueprint(blueprintId: string): Promise<string> {
    const response = await this.http.request<string>(`/blueprint/${blueprintId}`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Execute Blueprint
 *
 * @param blueprintId - The blueprint_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async executeBlueprint(blueprintId: string, body?: models.ExecuteBlueprintRequest): Promise<string> {
    const response = await this.http.request<string>(`/blueprint/${blueprintId}/execute`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Blueprint Tasks
 *
 * @param blueprintId - The blueprint_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getBlueprintTasks(blueprintId: string): Promise<string> {
    const response = await this.http.request<string>(`/blueprint/${blueprintId}/task`, {
      method: "GET",
    });

    return response;
  }

/**
 * Create Blueprint Task
 *
 * @param blueprintId - The blueprint_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async createBlueprintTask(blueprintId: string, body: models.AddBlueprintTaskRequest): Promise<string> {
    const response = await this.http.request<string>(`/blueprint/${blueprintId}/task`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Update Blueprint Task
 *
 * @param blueprintId - The blueprint_id parameter
 * @param taskId - The task_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateBlueprintTask(blueprintId: string, taskId: string, body: models.UpdateBlueprintTaskRequest): Promise<string> {
    const response = await this.http.request<string>(`/blueprint/${blueprintId}/task/${taskId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Blueprint Task
 *
 * @param blueprintId - The blueprint_id parameter
 * @param taskId - The task_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteBlueprintTask(blueprintId: string, taskId: string): Promise<string> {
    const response = await this.http.request<string>(`/blueprint/${blueprintId}/task/${taskId}`, {
      method: "DELETE",
    });

    return response;
  }

}
