/**
 * ConfidenceScoring resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';

export class ConfidenceScoringResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get Scoring Job
 *
 * @param jobId - The job_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getScoringJob(jobId: string): Promise<string> {
    const response = await this.http.request<string>(`/confidence-scoring/job/${jobId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * List Scoring Jobs
 *
 * @param agentName - The agent_name parameter
 * @param agentVersion - The agent_version parameter
 * @param agentExecutionId - The agent_execution_id parameter
 * @param agentWorkflowName - The agent_workflow_name parameter
 * @param agentWorkflowVersion - The agent_workflow_version parameter
 * @param agentWorkflowExecutionId - The agent_workflow_execution_id parameter
 * @param toolId - The tool_id parameter
 * @param toolInstanceId - The tool_instance_id parameter
 * @param toolExecutionId - The tool_execution_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listScoringJobs(options?: { agentName?: string | null; agentVersion?: string | null; agentExecutionId?: string | null; agentWorkflowName?: string | null; agentWorkflowVersion?: string | null; agentWorkflowExecutionId?: string | null; toolId?: string | null; toolInstanceId?: string | null; toolExecutionId?: string | null }): AsyncIterable<models.ScoringJobRecord> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      agent_name: options?.agentName ?? undefined,
      agent_version: options?.agentVersion ?? undefined,
      agent_execution_id: options?.agentExecutionId ?? undefined,
      agent_workflow_name: options?.agentWorkflowName ?? undefined,
      agent_workflow_version: options?.agentWorkflowVersion ?? undefined,
      agent_workflow_execution_id: options?.agentWorkflowExecutionId ?? undefined,
      tool_id: options?.toolId ?? undefined,
      tool_instance_id: options?.toolInstanceId ?? undefined,
      tool_execution_id: options?.toolExecutionId ?? undefined,
    };

    yield* paginate<models.ScoringJobRecord>(async (cursor) => {
      const response = await this.http.request<models.ScoringJobRecord[]>("/confidence-scoring/jobs", {
        method: "GET",
        params: {
          ...queryParams,
          offset: cursor,
        },
      });
      return {
        items: response ?? [],
      };
    });
  }

/**
 * Get Scoring Jobs Summary
 *
 * @param primary - The primary parameter
 * @param secondary - The secondary parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getScoringJobsSummary(primary: string, options?: { secondary?: string | null }): Promise<models.ScoreSummary> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      primary: primary,
      secondary: options?.secondary ?? undefined,
    };

    const response = await this.http.request<models.ScoreSummary>("/confidence-scoring/summary", {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

}
