/**
 * Track and analyze confidence scores
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class ConfidenceScoringResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get a scoring job
 *
 * Retrieve a single confidence scoring job by its ID, including its current status and score if completed.
 *
 * @param jobId - Unique identifier of the scoring job to retrieve.
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getScoringJob(jobId: string): Promise<models.ScoringJobRecord> {
    const response = await this.http.request<models.ScoringJobRecord>(`/confidence-scoring/job/${jobId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * List scoring jobs
 *
 * List confidence scoring jobs, optionally filtered by identity context fields. All filters are combined with AND logic.
 *
 * @param agentName - Filter by agent name.
 * @param agentVersion - Filter by agent version.
 * @param agentSessionId - Filter by agent session ID.
 * @param agentWorkflowName - Filter by workflow name.
 * @param agentWorkflowVersion - Filter by workflow version.
 * @param agentWorkflowSessionId - Filter by workflow session ID.
 * @param toolId - Filter by tool identifier.
 * @param toolInstanceId - Filter by tool instance identifier.
 * @param toolExecutionId - Filter by tool execution identifier.
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async listScoringJobs(options?: { agentName?: string | null; agentVersion?: string | null; agentSessionId?: string | null; agentWorkflowName?: string | null; agentWorkflowVersion?: string | null; agentWorkflowSessionId?: string | null; toolId?: string | null; toolInstanceId?: string | null; toolExecutionId?: string | null }): Promise<models.ScoringJobRecord[]> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      agent_name: options?.agentName ?? undefined,
      agent_version: options?.agentVersion ?? undefined,
      agent_session_id: options?.agentSessionId ?? undefined,
      agent_workflow_name: options?.agentWorkflowName ?? undefined,
      agent_workflow_version: options?.agentWorkflowVersion ?? undefined,
      agent_workflow_session_id: options?.agentWorkflowSessionId ?? undefined,
      tool_id: options?.toolId ?? undefined,
      tool_instance_id: options?.toolInstanceId ?? undefined,
      tool_execution_id: options?.toolExecutionId ?? undefined,
    };

    const response = await this.http.request<models.ScoringJobRecord[]>("/confidence-scoring/jobs", {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * Get scoring summary
 *
 * Get an aggregated summary of confidence scores. Requires a primary filter; an optional secondary filter narrows results further. Filters use the format "field:value", where field is any identity context field name.
 *
 * @param primary - Primary filter in "field:value" format, where field is an identity context field name (e.g. "agent_name:my-agent" or "agent_session_id:sess_abc123").
 * @param secondary - Optional secondary filter in the same "field:value" format to further narrow results (e.g. "agent_version:1.2.0").
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getScoringJobsSummary(primary: string, options?: { secondary?: string | null }): Promise<models.ScoreSummary> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      primary: primary,
      secondary: options?.secondary ?? undefined,
    };

    const response = await this.http.request<models.ScoreSummary>("/confidence-scoring/summary", {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

}
