/**
 * Track and analyze confidence scores
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class ConfidenceScoringResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get a scoring job
 *
 * Retrieve a single confidence scoring job by its ID, including its current status and score if completed.
 *
 * @param jobId - Unique identifier of the scoring job to retrieve.
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getScoringJob(jobId: string): Promise<models.ScoringJobResponse> {
    const response = await this.http.request<models.ScoringJobResponse>(`/confidence-scoring/job/${jobId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * List scoring jobs
 *
 * List confidence scoring jobs, optionally filtered by identity context fields. All filters are combined with AND logic.
 *
 * @param agentName - Filter by agent name.
 * @param agentVersion - Filter by agent version.
 * @param agentSessionId - Filter by agent session ID.
 * @param agentWorkflowName - Filter by workflow name.
 * @param agentWorkflowVersion - Filter by workflow version.
 * @param agentWorkflowSessionId - Filter by workflow session ID.
 * @param toolId - Filter by tool identifier.
 * @param toolInstanceId - Filter by tool instance identifier.
 * @param toolExecutionId - Filter by tool execution identifier.
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async listScoringJobs(options?: { agentName?: string | null; agentVersion?: string | null; agentSessionId?: string | null; agentWorkflowName?: string | null; agentWorkflowVersion?: string | null; agentWorkflowSessionId?: string | null; toolId?: string | null; toolInstanceId?: string | null; toolExecutionId?: string | null }): Promise<models.ScoringJobResponse[]> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      agent_name: options?.agentName ?? undefined,
      agent_version: options?.agentVersion ?? undefined,
      agent_session_id: options?.agentSessionId ?? undefined,
      agent_workflow_name: options?.agentWorkflowName ?? undefined,
      agent_workflow_version: options?.agentWorkflowVersion ?? undefined,
      agent_workflow_session_id: options?.agentWorkflowSessionId ?? undefined,
      tool_id: options?.toolId ?? undefined,
      tool_instance_id: options?.toolInstanceId ?? undefined,
      tool_execution_id: options?.toolExecutionId ?? undefined,
    };

    const response = await this.http.request<models.ScoringJobResponse[]>("/confidence-scoring/jobs", {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

}
