/**
 * Content resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class ContentResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List datasource content
 *
 * List files and directories in a datasource with optional filtering and pagination
 *
 * @param datasourceId - The datasource_id parameter
 * @param prefix - Filter content by path prefix
 * @param continuationToken - Token for pagination to get next page of results
 * @param limit - Maximum number of items to return (1-10000)
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async listDatasourceContent(datasourceId: string, options?: { prefix?: string | null; continuationToken?: string | null; limit?: number }): Promise<models.ListContentResponse> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      prefix: options?.prefix ?? undefined,
      continuation_token: options?.continuationToken ?? undefined,
      limit: options?.limit ?? undefined,
    };

    const response = await this.http.request<models.ListContentResponse>(`/datasource/${datasourceId}/content`, {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * Upload Content
 *
 * Proxy upload with zero-copy streaming.

This endpoint maintains the multipart form data structure and streams
it directly to the backend service without buffering files in memory.
The multipart parsing happens on the backend service side.
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async uploadDatasourceContent(datasourceId: string): Promise<models.UploadContentResponse> {
    const response = await this.http.request<models.UploadContentResponse>(`/datasource/${datasourceId}/content`, {
      method: "POST",
    });

    return response;
  }

/**
 * Stream upload progress events
 *
 * Subscribe to real-time upload progress updates via Server-Sent Events
 *
 * @param uploadId - The upload_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async streamUploadProgress(uploadId: string): Promise<void> {
    const response = await this.http.request<void>(`/uploads/${uploadId}/progress`, {
      method: "GET",
    });

    return response;
  }

/**
 * Get upload status
 *
 * Get the current status of a content upload operation
 *
 * @param datasourceId - The datasource_id parameter
 * @param uploadId - The upload_id parameter
 *
 * @returns Upload status information
 *
 * @throws {ApiError} If the request fails
 */
  async getDatasourceUploadStatus(datasourceId: string, uploadId: string): Promise<string> {
    const response = await this.http.request<string>(`/datasource/${datasourceId}/content/upload-status/${uploadId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Stream upload progress events (legacy)
 *
 * Subscribe to real-time upload progress updates via Server-Sent Events. Consider using /uploads/{upload_id}/progress instead.
 *
 * @param datasourceId - The datasource_id parameter
 * @param uploadId - The upload_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async streamDatasourceUploadProgress(datasourceId: string, uploadId: string): Promise<void> {
    const response = await this.http.request<void>(`/datasource/${datasourceId}/content/upload-progress/${uploadId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Get content metadata
 *
 * Get metadata information for a file or directory in the datasource
 *
 * @param datasourceId - The datasource_id parameter
 * @param path - The path parameter
 *
 * @returns Content metadata information
 *
 * @throws {ApiError} If the request fails
 */
  async getDatasourceContentMetadata(datasourceId: string, path: string): Promise<models.GetContentResponse> {
    const response = await this.http.request<models.GetContentResponse>(`/datasource/${datasourceId}/content/${path}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Delete content
 *
 * Delete a file or directory from the datasource
 *
 * @param datasourceId - The datasource_id parameter
 * @param path - The path parameter
 *
 * @returns Content successfully deleted
 *
 * @throws {ApiError} If the request fails
 */
  async deleteDatasourceContent(datasourceId: string, path: string): Promise<models.DeleteContentResponse> {
    const response = await this.http.request<models.DeleteContentResponse>(`/datasource/${datasourceId}/content/${path}`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Download content file
 *
 * Download a file from the datasource with streaming support for large files
 *
 * @param datasourceId - The datasource_id parameter
 * @param path - The path parameter
 *
 * @throws {ApiError} If the request fails
 */
  async downloadDatasourceContent(datasourceId: string, path: string): Promise<void> {
    const response = await this.http.request<void>(`/datasource/${datasourceId}/content/${path}/download`, {
      method: "GET",
    });

    return response;
  }

}
