/**
 * Content resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';
import type { UploadFile } from '../upload.js';

export class ContentResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Content
 *
 * @param datasourceId - The datasource_id parameter
 * @param prefix - Filter content by path prefix
 * @param continuationToken - Token for pagination
 * @param limit - Maximum items to return
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listContent(datasourceId: string, options?: { prefix?: string | null; continuationToken?: string | null; limit?: number }): AsyncIterable<string> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      prefix: options?.prefix ?? undefined,
      continuation_token: options?.continuationToken ?? undefined,
      limit: options?.limit,
    };

    yield* paginate<string>(async (cursor) => {
      const response = await this.http.request<string[]>(`/datasources/${datasourceId}/content`, {
        method: "GET",
        params: {
          ...queryParams,
          offset: cursor,
        },
      });
      return {
        items: response ?? [],
      };
    });
  }

/**
 * Upload Content
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async uploadContent(datasourceId: string, file: ReadableStream<Uint8Array> | Blob | File, fileName: string): Promise<string> {
    const path = `/datasources/${datasourceId}/content`;
    return this.http.upload<string>(path, [
      { fieldName: 'file', fileName: fileName, content: file },
    ]);
  }

/**
 * Stream Upload Progress
 *
 * @param uploadId - The upload_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async streamUploadProgress(uploadId: string): Promise<void> {
    const response = await this.http.request<void>(`/uploads/${uploadId}/progress`, {
      method: "GET",
    });

    return response;
  }

/**
 * Get Content Metadata
 *
 * @param datasourceId - The datasource_id parameter
 * @param path - The path parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getContentMetadata(datasourceId: string, path: string): Promise<string> {
    const response = await this.http.request<string>(`/datasources/${datasourceId}/content/${path}/metadata`, {
      method: "GET",
    });

    return response;
  }

/**
 * Download Content
 *
 * @param datasourceId - The datasource_id parameter
 * @param path - The path parameter
 *
 * @throws {ApiError} If the request fails
 */
  async downloadContent(datasourceId: string, path: string): Promise<void> {
    const response = await this.http.request<void>(`/datasources/${datasourceId}/content/${path}/download`, {
      method: "GET",
    });

    return response;
  }

/**
 * Trigger Ingest
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async triggerIngest(datasourceId: string): Promise<string> {
    const response = await this.http.request<string>(`/datasources/${datasourceId}/trigger-ingest`, {
      method: "POST",
    });

    return response;
  }

/**
 * Delete Content
 *
 * @param datasourceId - The datasource_id parameter
 * @param path - The path parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteContent(datasourceId: string, path: string): Promise<string> {
    const response = await this.http.request<string>(`/datasources/${datasourceId}/content/${path}`, {
      method: "DELETE",
    });

    return response;
  }

}
