/**
 * Upload, manage, and ingest content files
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import type { UploadFile } from '../upload.js';

export class ContentResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Stream upload progress events
 *
 * Subscribe to real-time upload progress updates via Server-Sent Events
 *
 * @param uploadId - The upload_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async streamUploadProgress(uploadId: string): Promise<void> {
    const response = await this.http.request<void>(`/uploads/${uploadId}/progress`, {
      method: "GET",
    });

    return response;
  }

/**
 * Trigger ingest
 *
 * Trigger ingestion for a datasource
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async triggerIngest(datasourceId: string): Promise<string> {
    const response = await this.http.request<string>(`/datasource/${datasourceId}/trigger-ingest`, {
      method: "GET",
    });

    return response;
  }

/**
 * List Content
 *
 * @param datasourceId - The datasource_id parameter
 * @param prefix - Filter content by path prefix
 * @param continuationToken - Token for pagination
 * @param limit - Maximum items to return
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async listContent(datasourceId: string, options?: { prefix?: string | null; continuationToken?: string | null; limit?: number }): Promise<string> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      prefix: options?.prefix ?? undefined,
      continuation_token: options?.continuationToken ?? undefined,
      limit: options?.limit ?? undefined,
    };

    const response = await this.http.request<string>(`/v2/datasources/${datasourceId}/content`, {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * Upload Content
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async uploadContent(datasourceId: string, file: ReadableStream<Uint8Array> | Blob | File, fileName: string): Promise<string> {
    const path = `/v2/datasources/${datasourceId}/content`;
    return this.http.upload<string>(path, [
      { fieldName: 'file', fileName: fileName, content: file },
    ]);
  }

/**
 * Stream Upload Progress
 *
 * @param uploadId - The upload_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async streamUploadProgress(uploadId: string): Promise<void> {
    const response = await this.http.request<void>(`/v2/uploads/${uploadId}/progress`, {
      method: "GET",
    });

    return response;
  }

/**
 * Trigger Ingest
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async triggerIngest(datasourceId: string): Promise<string> {
    const response = await this.http.request<string>(`/v2/datasources/${datasourceId}/trigger-ingest`, {
      method: "POST",
    });

    return response;
  }

}
