/**
 * Manage data source connections
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { ContentResource } from './content.js';
import { DataElementsResource } from './data-elements.js';

export class DatasourcesResource {
  public readonly content: ContentResource;
  public readonly dataElements: DataElementsResource;

  constructor(private readonly http: HttpClient) {
    this.content = new ContentResource(http);
    this.dataElements = new DataElementsResource(http);
  }

/**
 * Get Datasource
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDatasource(datasourceId: string): Promise<models.Datasource> {
    const response = await this.http.request<models.Datasource>(`/datasource/${datasourceId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Datasource
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateDatasource(datasourceId: string, body: models.DatasourceServiceClientModelsUpdateDatasourceRequestUpdateDatasourceRequest): Promise<models.UpdateDatasourceResponse> {
    const response = await this.http.request<models.UpdateDatasourceResponse>(`/datasource/${datasourceId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Datasource
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteDatasource(datasourceId: string): Promise<models.DeleteDatasourceResponse> {
    const response = await this.http.request<models.DeleteDatasourceResponse>(`/datasource/${datasourceId}`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * List Datasources
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async listDatasources(): Promise<models.DatasourceListResponse> {
    const response = await this.http.request<models.DatasourceListResponse>("/v2/datasources", {
      method: "GET",
    });

    return response;
  }

/**
 * Create Datasource
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async createDatasource(body: models.CreateDatasourceRequest): Promise<models.DatasourceResponse> {
    const response = await this.http.request<models.DatasourceResponse>("/v2/datasources", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Datasource
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDatasource(datasourceId: string): Promise<models.DatasourceResponse> {
    const response = await this.http.request<models.DatasourceResponse>(`/v2/datasources/${datasourceId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Datasource
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateDatasource(datasourceId: string, body: models.GatewayServiceV2ModelsDatasourcesUpdateDatasourceRequest): Promise<models.DatasourceResponse> {
    const response = await this.http.request<models.DatasourceResponse>(`/v2/datasources/${datasourceId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Datasource
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteDatasource(datasourceId: string): Promise<string> {
    const response = await this.http.request<string>(`/v2/datasources/${datasourceId}`, {
      method: "DELETE",
    });

    return response;
  }

}
