/**
 * DatasourcesDataelements resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class DatasourcesDataelementsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get Data Elements
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElements(datasourceId: string): Promise<models.DataElement[]> {
    const response = await this.http.request<models.DataElement[]>(`/datasource/${datasourceId}/data_element`, {
      method: "GET",
    });

    return response;
  }

/**
 * Add Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async addDataElement(datasourceId: string, body: models.AddDataElementRequest): Promise<models.AddDataElementResponse> {
    const response = await this.http.request<models.AddDataElementResponse>(`/datasource/${datasourceId}/data_element`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElement(datasourceId: string, dataElementId: string): Promise<models.DataElement> {
    const response = await this.http.request<models.DataElement>(`/datasource/${datasourceId}/data_element/${dataElementId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateDataElement(datasourceId: string, dataElementId: string, body: models.DatasourceServiceClientModelsUpdateDataElementRequestUpdateDataElementRequest): Promise<models.UpdateDataElementResponse> {
    const response = await this.http.request<models.UpdateDataElementResponse>(`/datasource/${datasourceId}/data_element/${dataElementId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteDataElement(datasourceId: string, dataElementId: string): Promise<models.DeleteDataElementResponse> {
    const response = await this.http.request<models.DeleteDataElementResponse>(`/datasource/${datasourceId}/data_element/${dataElementId}`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Get Data Elements By Filters
 *
 * @param datasourceId - The datasource_id parameter
 * @param regexFilter - The regex_filter parameter
 * @param mediaTypeFilters - The media_type_filters parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElementsByFilters(datasourceId: string, body?: models.DataElementFilterRequest, options?: { regexFilter?: string; mediaTypeFilters?: string[] }): Promise<models.DataElement[]> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      regex_filter: options?.regexFilter,
      media_type_filters: options?.mediaTypeFilters?.join(','),
    };

    const response = await this.http.request<models.DataElement[]>(`/datasource/${datasourceId}/data_elements_by_filters`, {
      method: "POST",
      params: queryParams,
      body,
    });

    return response;
  }

/**
 * Get Data Element Metadata
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElementMetadata(datasourceId: string, dataElementId: string): Promise<models.GetDataElementMetadataResponse> {
    const response = await this.http.request<models.GetDataElementMetadataResponse>(`/datasource/${datasourceId}/data_element/${dataElementId}/metadata`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Data Element Metadata
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateDataElementMetadata(datasourceId: string, dataElementId: string, body: models.PutDataElementMetadataRequest): Promise<models.PutDataElementMetadataResponse> {
    const response = await this.http.request<models.PutDataElementMetadataResponse>(`/datasource/${datasourceId}/data_element/${dataElementId}/metadata`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Get Data Element Metadata Result
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 * @param requestId - The request_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElementMetadataResult(datasourceId: string, dataElementId: string, requestId: string): Promise<models.GetDataElementMetadataResultResponse> {
    const response = await this.http.request<models.GetDataElementMetadataResultResponse>(`/datasource/${datasourceId}/data_element/${dataElementId}/metadata/result/${requestId}`, {
      method: "GET",
    });

    return response;
  }

}
