/**
 * DatasourcesRag resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class DatasourcesRagResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get Rag Config
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getRagConfig(datasourceId: string): Promise<models.RagConfig> {
    const response = await this.http.request<models.RagConfig>(`/datasource/${datasourceId}/rag_config`, {
      method: "GET",
    });

    return response;
  }

/**
 * Add Rag Config
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async addRagConfig(datasourceId: string, body: models.AddRagConfigRequest): Promise<models.AddRagConfigResponse> {
    const response = await this.http.request<models.AddRagConfigResponse>(`/datasource/${datasourceId}/rag_config`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Update Rag Config
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateRagConfig(datasourceId: string, body: models.UpdateRagConfigRequest): Promise<models.UpdateRagConfigResponse> {
    const response = await this.http.request<models.UpdateRagConfigResponse>(`/datasource/${datasourceId}/rag_config`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Rag Config
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteRagConfig(datasourceId: string): Promise<string> {
    const response = await this.http.request<string>(`/datasource/${datasourceId}/rag_config`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Get Chunking Strategy
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getChunkingStrategy(datasourceId: string): Promise<models.RagChunkingStrategy> {
    const response = await this.http.request<models.RagChunkingStrategy>(`/datasource/${datasourceId}/chunking_strategy`, {
      method: "GET",
    });

    return response;
  }

/**
 * Add Chunking Strategy
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async addChunkingStrategy(datasourceId: string, body: models.AddChunkingStrategyRequest): Promise<models.AddChunkingStrategyResponse> {
    const response = await this.http.request<models.AddChunkingStrategyResponse>(`/datasource/${datasourceId}/chunking_strategy`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Update Chunking Strategy
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateChunkingStrategy(datasourceId: string, body: models.UpdateChunkingStrategyRequest): Promise<models.UpdateChunkingStrategyResponse> {
    const response = await this.http.request<models.UpdateChunkingStrategyResponse>(`/datasource/${datasourceId}/chunking_strategy`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Chunking Strategy
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteChunkingStrategy(datasourceId: string): Promise<models.DeleteChunkingStrategyResponse> {
    const response = await this.http.request<models.DeleteChunkingStrategyResponse>(`/datasource/${datasourceId}/chunking_strategy`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Reprocess Datasource Metadata
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async reprocessDatasourceMetadata(datasourceId: string, body: models.ReprocessDatasourceRequest): Promise<models.ReprocessDatasourceResponse> {
    const response = await this.http.request<models.ReprocessDatasourceResponse>(`/datasource/${datasourceId}/reprocess_metadata`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Reprocess Metadata Status
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getReprocessMetadataStatus(datasourceId: string): Promise<models.GetReprocessStatusResponse> {
    const response = await this.http.request<models.GetReprocessStatusResponse>(`/datasource/${datasourceId}/reprocess_metadata/status`, {
      method: "GET",
    });

    return response;
  }

/**
 * Patch Rag Config Metadata
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async patchRagConfigMetadata(datasourceId: string, body: models.PatchRagConfigMetadataRequest): Promise<models.PatchRagConfigMetadataResponse> {
    const response = await this.http.request<models.PatchRagConfigMetadataResponse>(`/datasource/${datasourceId}/rag_config/metadata`, {
      method: "PATCH",
      body,
    });

    return response;
  }

}
