/**
 * DataElementMetadata resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class DataElementMetadataResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get Data Element Metadata
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElementMetadata(datasourceId: string, dataElementId: string): Promise<string> {
    const response = await this.http.request<string>(`/datasources/${datasourceId}/data-elements/${dataElementId}/metadata`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Data Element Metadata
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateDataElementMetadata(datasourceId: string, dataElementId: string, body: models.DataElementMetadata): Promise<string> {
    const response = await this.http.request<string>(`/datasources/${datasourceId}/data-elements/${dataElementId}/metadata`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Get Data Element Metadata Result
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 * @param requestId - The request_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElementMetadataResult(datasourceId: string, dataElementId: string, requestId: string): Promise<string> {
    const response = await this.http.request<string>(`/datasources/${datasourceId}/data-elements/${dataElementId}/metadata/result/${requestId}`, {
      method: "GET",
    });

    return response;
  }

}
