/**
 * Datasources resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';

export class DatasourcesResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Datasources
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listDatasources(): AsyncIterable<models.DatasourceResponse> {
    yield* paginate<models.DatasourceResponse>(async (cursor) => {
      const response = await this.http.request<models.DatasourceListResponse>("/v2/datasources", {
        method: "GET",
        params: {
          offset: cursor,
        },
      });
      return {
        items: response.datasources ?? [],
      };
    });
  }

/**
 * Create Datasource
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async createDatasource(body: models.CreateDatasourceRequest): Promise<models.DatasourceResponse> {
    const response = await this.http.request<models.DatasourceResponse>("/v2/datasources", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Datasource
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDatasource(datasourceId: string): Promise<models.DatasourceResponse> {
    const response = await this.http.request<models.DatasourceResponse>(`/v2/datasources/${datasourceId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Datasource
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateDatasource(datasourceId: string, body: models.GatewayServiceV2ModelsDatasourcesUpdateDatasourceRequest): Promise<models.DatasourceResponse> {
    const response = await this.http.request<models.DatasourceResponse>(`/v2/datasources/${datasourceId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Datasource
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteDatasource(datasourceId: string): Promise<string> {
    const response = await this.http.request<string>(`/v2/datasources/${datasourceId}`, {
      method: "DELETE",
    });

    return response;
  }

}
