/**
 * Dataelements resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class DataelementsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get Data Elements
 *
 * @param datasourceId - The datasource_id parameter
 * @param offset - Number of items to skip
 * @param limit - Maximum number of items to return
 * @param sortBy - Field to sort by
 * @param sortOrder - Sort order (asc or desc)
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElements(datasourceId: string, options?: { offset?: number; limit?: number; sortBy?: string | null; sortOrder?: string | null }): Promise<models.DataElement[]> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
      sort_by: options?.sortBy ?? undefined,
      sort_order: options?.sortOrder ?? undefined,
    };

    const response = await this.http.request<models.DataElement[]>(`/datasource/${datasourceId}/data_element`, {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * Add Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async addDataElement(datasourceId: string, body: models.AddDataElementRequest): Promise<models.AddDataElementResponse> {
    const response = await this.http.request<models.AddDataElementResponse>(`/datasource/${datasourceId}/data_element`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElement(datasourceId: string, dataElementId: string): Promise<models.DataElement> {
    const response = await this.http.request<models.DataElement>(`/datasource/${datasourceId}/data_element/${dataElementId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateDataElement(datasourceId: string, dataElementId: string, body: models.UpdateDataElementRequest): Promise<models.UpdateDataElementResponse> {
    const response = await this.http.request<models.UpdateDataElementResponse>(`/datasource/${datasourceId}/data_element/${dataElementId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteDataElement(datasourceId: string, dataElementId: string): Promise<models.DeleteDataElementResponse> {
    const response = await this.http.request<models.DeleteDataElementResponse>(`/datasource/${datasourceId}/data_element/${dataElementId}`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Get Data Elements By Filters
 *
 * @param datasourceId - The datasource_id parameter
 * @param regexFilter - The regex_filter parameter
 * @param mediaTypeFilters - The media_type_filters parameter
 * @param offset - Number of items to skip
 * @param limit - Maximum number of items to return
 * @param sortBy - Field to sort by
 * @param sortOrder - Sort order (asc or desc)
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElementsByFilters(datasourceId: string, body?: models.DataElementFilterRequest, options?: { regexFilter?: string; mediaTypeFilters?: string[]; offset?: number; limit?: number; sortBy?: string | null; sortOrder?: string | null }): Promise<models.DataElement[]> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      regex_filter: options?.regexFilter ?? undefined,
      media_type_filters: options?.mediaTypeFilters ?? undefined,
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
      sort_by: options?.sortBy ?? undefined,
      sort_order: options?.sortOrder ?? undefined,
    };

    const response = await this.http.request<models.DataElement[]>(`/datasource/${datasourceId}/data_elements_by_filters`, {
      method: "POST",
      params: queryParams,
      body,
    });

    return response;
  }

}
