/**
 * DatasourcesTag resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class DatasourcesTagResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get Tag Config
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getTagConfig(datasourceId: string): Promise<models.TagConfig> {
    const response = await this.http.request<models.TagConfig>(`/datasource/${datasourceId}/tag_config`, {
      method: "GET",
    });

    return response;
  }

/**
 * Add Tag Config
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async addTagConfig(datasourceId: string, body: models.AddTagConfigRequest): Promise<models.AddTagConfigResponse> {
    const response = await this.http.request<models.AddTagConfigResponse>(`/datasource/${datasourceId}/tag_config`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Update Tag Config
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateTagConfig(datasourceId: string, body: models.UpdateTagConfigRequest): Promise<models.UpdateTagConfigResponse> {
    const response = await this.http.request<models.UpdateTagConfigResponse>(`/datasource/${datasourceId}/tag_config`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Tag Config
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteTagConfig(datasourceId: string): Promise<string> {
    const response = await this.http.request<string>(`/datasource/${datasourceId}/tag_config`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Get Tag Table Info
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getTagTableInfo(datasourceId: string, tableName: string): Promise<models.TagTableInfo> {
    const response = await this.http.request<models.TagTableInfo>(`/datasource/${datasourceId}/tag_table_info/${tableName}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Add Tag Table Info
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async addTagTableInfo(datasourceId: string, tableName: string, body: models.AddTagTableRequest): Promise<models.AddTagTableResponse> {
    const response = await this.http.request<models.AddTagTableResponse>(`/datasource/${datasourceId}/tag_table_info/${tableName}`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Update Tag Table Info
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateTagTableInfo(datasourceId: string, tableName: string, body: models.UpdateTagTableRequest): Promise<models.UpdateTagTableResponse> {
    const response = await this.http.request<models.UpdateTagTableResponse>(`/datasource/${datasourceId}/tag_table_info/${tableName}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Tag Table Info
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteTagTableInfo(datasourceId: string, tableName: string): Promise<models.DeleteTagTableResponse> {
    const response = await this.http.request<models.DeleteTagTableResponse>(`/datasource/${datasourceId}/tag_table_info/${tableName}`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Get All Tag Table Info
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getAllTagTableInfo(datasourceId: string): Promise<models.TagTableInfo[]> {
    const response = await this.http.request<models.TagTableInfo[]>(`/datasource/${datasourceId}/tag_table_info`, {
      method: "GET",
    });

    return response;
  }

/**
 * Get Tag Column Info
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 * @param columnName - The column_name parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getTagColumnInfo(datasourceId: string, tableName: string, columnName: string): Promise<models.TagColumnInfo> {
    const response = await this.http.request<models.TagColumnInfo>(`/datasource/${datasourceId}/tag_table_info/${tableName}/column_info/${columnName}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Add Tag Column Info
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 * @param columnName - The column_name parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async addTagColumnInfo(datasourceId: string, tableName: string, columnName: string, body: models.AddTagColumnRequest): Promise<models.AddTagColumnResponse> {
    const response = await this.http.request<models.AddTagColumnResponse>(`/datasource/${datasourceId}/tag_table_info/${tableName}/column_info/${columnName}`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Update Tag Column Info
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 * @param columnName - The column_name parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateTagColumnInfo(datasourceId: string, tableName: string, columnName: string, body: models.UpdateTagColumnRequest): Promise<models.UpdateTagColumnResponse> {
    const response = await this.http.request<models.UpdateTagColumnResponse>(`/datasource/${datasourceId}/tag_table_info/${tableName}/column_info/${columnName}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Tag Column Info
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 * @param columnName - The column_name parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteTagColumnInfo(datasourceId: string, tableName: string, columnName: string): Promise<models.DeleteTagTableResponse> {
    const response = await this.http.request<models.DeleteTagTableResponse>(`/datasource/${datasourceId}/tag_table_info/${tableName}/column_info/${columnName}`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Get All Tag Column Info
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getAllTagColumnInfo(datasourceId: string, tableName: string): Promise<models.TagColumnInfo[]> {
    const response = await this.http.request<models.TagColumnInfo[]>(`/datasource/${datasourceId}/tag_table_info/${tableName}/column_info`, {
      method: "GET",
    });

    return response;
  }

}
