/**
 * Manage data elements within datasources
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class DataElementsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElement(datasourceId: string, dataElementId: string): Promise<models.DataElement> {
    const response = await this.http.request<models.DataElement>(`/datasource/${datasourceId}/data_element/${dataElementId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateDataElement(datasourceId: string, dataElementId: string, body: models.DatasourceServiceClientModelsUpdateDataElementRequestUpdateDataElementRequest): Promise<models.UpdateDataElementResponse> {
    const response = await this.http.request<models.UpdateDataElementResponse>(`/datasource/${datasourceId}/data_element/${dataElementId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * List Data Elements
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async listDataElements(datasourceId: string): Promise<models.DataElementResponse[]> {
    const response = await this.http.request<models.DataElementResponse[]>(`/v2/datasources/${datasourceId}/data-elements`, {
      method: "GET",
    });

    return response;
  }

/**
 * Get Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElement(datasourceId: string, dataElementId: string): Promise<models.DataElementResponse> {
    const response = await this.http.request<models.DataElementResponse>(`/v2/datasources/${datasourceId}/data-elements/${dataElementId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateDataElement(datasourceId: string, dataElementId: string, body: models.GatewayServiceV2ModelsDataElementsUpdateDataElementRequest): Promise<models.DataElementResponse> {
    const response = await this.http.request<models.DataElementResponse>(`/v2/datasources/${datasourceId}/data-elements/${dataElementId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Search Data Elements
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async searchDataElements(datasourceId: string, body: models.DataElementSearchRequest): Promise<models.DataElementResponse[]> {
    const response = await this.http.request<models.DataElementResponse[]>(`/v2/datasources/${datasourceId}/data-elements/search`, {
      method: "POST",
      body,
    });

    return response;
  }

}
