/**
 * Datasources resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { ContentResource } from './content.js';
import { DataelementsResource } from './dataelements.js';
import { RagResource } from './rag.js';
import { TagResource } from './tag.js';

export class DatasourcesResource {
  public readonly content: ContentResource;
  public readonly dataelements: DataelementsResource;
  public readonly rag: RagResource;
  public readonly tag: TagResource;

  constructor(private readonly http: HttpClient) {
    this.content = new ContentResource(http);
    this.dataelements = new DataelementsResource(http);
    this.rag = new RagResource(http);
    this.tag = new TagResource(http);
  }

/**
 * Add Datasource
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async addDatasource(body: models.AddDatasourceRequest): Promise<models.AddDatasourceResponse> {
    const response = await this.http.request<models.AddDatasourceResponse>("/datasource", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Datasource
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDatasource(datasourceId: string): Promise<models.Datasource> {
    const response = await this.http.request<models.Datasource>(`/datasource/${datasourceId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Datasource
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateDatasource(datasourceId: string, body: models.UpdateDatasourceRequest): Promise<models.UpdateDatasourceResponse> {
    const response = await this.http.request<models.UpdateDatasourceResponse>(`/datasource/${datasourceId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Datasource
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteDatasource(datasourceId: string): Promise<models.DeleteDatasourceResponse> {
    const response = await this.http.request<models.DeleteDatasourceResponse>(`/datasource/${datasourceId}`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Get All Datasource Ids
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getAllDatasourceIds(): Promise<models.GetAllDatasourceIdsResponse> {
    const response = await this.http.request<models.GetAllDatasourceIdsResponse>("/project_datasource_ids", {
      method: "POST",
    });

    return response;
  }

}
