/**
 * DataElements resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';

export class DataElementsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Data Elements
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listDataElements(datasourceId: string): AsyncIterable<models.DataElementResponse> {
    yield* paginate<models.DataElementResponse>(async (cursor) => {
      const response = await this.http.request<models.DataElementResponse[]>(`/datasources/${datasourceId}/data-elements`, {
        method: "GET",
        params: {
          offset: cursor,
        },
      });
      return {
        items: response ?? [],
      };
    });
  }

/**
 * Create Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async createDataElement(datasourceId: string, body: models.CreateDataElementRequest): Promise<models.DataElementResponse> {
    const response = await this.http.request<models.DataElementResponse>(`/datasources/${datasourceId}/data-elements`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElement(datasourceId: string, dataElementId: string): Promise<models.DataElementResponse> {
    const response = await this.http.request<models.DataElementResponse>(`/datasources/${datasourceId}/data-elements/${dataElementId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateDataElement(datasourceId: string, dataElementId: string, body: models.UpdateDataElementRequest): Promise<models.DataElementResponse> {
    const response = await this.http.request<models.DataElementResponse>(`/datasources/${datasourceId}/data-elements/${dataElementId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async deleteDataElement(datasourceId: string, dataElementId: string): Promise<string> {
    const response = await this.http.request<string>(`/datasources/${datasourceId}/data-elements/${dataElementId}`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Search Data Elements
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async searchDataElements(datasourceId: string, body: models.DataElementSearchRequest): Promise<models.DataElementResponse[]> {
    const response = await this.http.request<models.DataElementResponse[]>(`/datasources/${datasourceId}/data-elements/search`, {
      method: "POST",
      body,
    });

    return response;
  }

}
