/**
 * Manage data elements within datasources
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';

export class DataElementsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDataElement(datasourceId: string, dataElementId: string): Promise<models.DataElementResponse> {
    const response = await this.http.request<models.DataElementResponse>(`/datasources/${datasourceId}/data-elements/${dataElementId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Data Element
 *
 * @param datasourceId - The datasource_id parameter
 * @param dataElementId - The data_element_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateDataElement(datasourceId: string, dataElementId: string, body: models.UpdateDataElementRequest): Promise<models.DataElementResponse> {
    const response = await this.http.request<models.DataElementResponse>(`/datasources/${datasourceId}/data-elements/${dataElementId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * List Data Elements
 *
 * @param datasourceId - The datasource_id parameter
 * @param cursor - Cursor for pagination
 * @param limit - Maximum items to return
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listDataElements(datasourceId: string, options?: { cursor?: string | null; limit?: number }): AsyncIterable<models.DataElementResponse> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      cursor: options?.cursor ?? undefined,
      limit: options?.limit ?? undefined,
    };

    yield* paginate<models.DataElementResponse>(async (cursor) => {
      const response = await this.http.request<models.DataElementListResponse>(`/datasources/${datasourceId}/data-elements`, {
        method: "GET",
        params: {
          ...queryParams,
          cursor: cursor,
        },
      });
      return {
        items: response.items ?? [],
      };
    });
  }

/**
 * Search Data Elements
 *
 * @param datasourceId - The datasource_id parameter
 * @param cursor - Cursor for pagination
 * @param limit - Maximum items to return
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async searchDataElements(datasourceId: string, body: models.DataElementSearchRequest, options?: { cursor?: string | null; limit?: number }): Promise<models.DataElementListResponse> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      cursor: options?.cursor ?? undefined,
      limit: options?.limit ?? undefined,
    };

    const response = await this.http.request<models.DataElementListResponse>(`/datasources/${datasourceId}/data-elements/search`, {
      method: "POST",
      params: queryParams,
      body,
    });

    return response;
  }

}
