/**
 * Documents resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';
import { streamSSE } from '../streaming.js';
import type { UploadFile } from '../upload.js';

export class DocumentsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Parse a document (async)
 *
 * Upload a document for asynchronous parsing. Returns a job ID to track progress.
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async parseDocument(file: ReadableStream<Uint8Array> | Blob | File, fileName: string): Promise<models.ParseDocumentResponse> {
    const path = "/v2/documents";
    return this.http.upload<models.ParseDocumentResponse>(path, [
      { fieldName: 'file', fileName: fileName, content: file },
    ]);
  }

/**
 * Parse a document (sync)
 *
 * Upload a document and block until parsing is complete. Returns the full parsed result.
 *
 * @param format - Result format: markdown, annotated, docling, json
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async processDocument(file: ReadableStream<Uint8Array> | Blob | File, fileName: string): Promise<models.ProcessDocumentResponse> {
    const path = "/v2/documents/process";
    return this.http.upload<models.ProcessDocumentResponse>(path, [
      { fieldName: 'file', fileName: fileName, content: file },
    ]);
  }

/**
 * Get document parsing status
 *
 * Check the status of a document parsing job, including progress statistics.
 *
 * @param jobId - The job_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDocumentStatus(jobId: string): Promise<models.DocumentStatus> {
    const response = await this.http.request<models.DocumentStatus>(`/v2/documents/${jobId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Get parsed document result
 *
 * Download the parsed result of a completed document parsing job.
 *
 * @param jobId - The job_id parameter
 * @param format - Result format: markdown, annotated, docling, json
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDocumentResult(jobId: string, options?: { format?: string }): Promise<string> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      format: options?.format,
    };

    const response = await this.http.request<string>(`/v2/documents/${jobId}/result`, {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * List child documents
 *
 * For container files (ZIP, TAR, EML), list the child documents extracted from the container.
 *
 * @param jobId - The job_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listDocumentChildren(jobId: string): AsyncIterable<models.DocumentChild> {
    yield* paginate<models.DocumentChild>(async (cursor) => {
      const response = await this.http.request<models.DocumentChild[]>(`/v2/documents/${jobId}/children`, {
        method: "GET",
        params: {
          offset: cursor,
        },
      });
      return {
        items: response ?? [],
      };
    });
  }

/**
 * Stream document parsing trace
 *
 * Subscribe to real-time parsing progress via Server-Sent Events.
 *
 * @param jobId - The job_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async *streamDocumentTrace(jobId: string): AsyncIterable<Record<string, unknown>> {
    const response = await this.http.request<Response>(`/v2/documents/${jobId}/trace`, {
      method: "GET",
      stream: true,
    });

    yield* streamSSE(response);
  }

}
