/**
 * Parse and transform documents into structured data
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';
import { streamSSE } from '../streaming.js';
import type { UploadFile } from '../upload.js';
import { z } from 'zod';
import { zodToJsonSchema } from '../schema.js';

export class DocumentsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List deep-transform jobs
 *
 * List the calling customer's deep-transform jobs, newest first. Scoped to the customer (and project, when a project header is set). Paginated via `offset`/`limit`.
 *
 * @param offset - Number of jobs to skip
 * @param limit - Maximum number of jobs to return
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listDeepTransforms(options?: { offset?: number; limit?: number }): AsyncIterable<models.DeepTransformJob> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
    };

    yield* paginate<models.DeepTransformJob>(async (cursor) => {
      const response = await this.http.request<models.DeepTransformJobList>("/documents/deep-transform", {
        method: "GET",
        params: {
          ...queryParams,
          offset: cursor,
        },
      });
      return {
        items: response.jobs ?? [],
      };
    });
  }

/**
 * Submit a deep-transform extraction from a file upload (async)
 *
 * Upload a document and submit an extraction against a JSON schema, returning immediately with a job id. To reuse an already-parsed document instead of uploading, use POST /documents/deep-transform/from-document. Poll status via GET /documents/deep-transform/{job_id} and download artifacts once it succeeds. Submission is idempotent on the (document, schema) pair.
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async submitDeepTransform(options: { file: string | File | Blob | ReadableStream<Uint8Array>; schema: string | Record<string, unknown> | z.ZodType; rootName?: string; guidance?: string; maxPages?: number }): Promise<models.SubmitDeepTransformResponse> {
    const _schema = options.schema instanceof z.ZodType
      ? zodToJsonSchema(options.schema)
      : options.schema;
    const path = "/documents/deep-transform";

    // Resolve file content
    let _fileContent: ReadableStream<Uint8Array> | Blob | File;
    let _fileName: string;
    if (typeof options.file === 'string') {
      const { createReadStream } = await import('node:fs');
      const { Readable } = await import('node:stream');
      _fileContent = Readable.toWeb(createReadStream(options.file)) as ReadableStream<Uint8Array>;
      _fileName = options.file.split('/').pop() ?? options.file;
    } else {
      _fileContent = options.file;
      _fileName = options.file instanceof File ? options.file.name : 'file';
    }

    // Build form fields from non-file smart params
    const formFields: Record<string, string> = {};
    if (typeof _schema === 'object' && _schema !== null) {
      formFields['schema'] = JSON.stringify(_schema);
    } else if (_schema != null) {
      formFields['schema'] = String(_schema);
    }
    if (options.rootName != null) {
      formFields['root_name'] = String(options.rootName);
    }
    if (options.guidance != null) {
      formFields['guidance'] = String(options.guidance);
    }
    if (options.maxPages != null) {
      formFields['max_pages'] = String(options.maxPages);
    }

    return this.http.upload<models.SubmitDeepTransformResponse>(path, [
      { fieldName: 'file', fileName: _fileName, content: _fileContent },
    ], { formFields });
  }

/**
 * Submit a deep-transform extraction reusing a parsed document (async)
 *
 * Submit an extraction that reuses an already-parsed document (by `document_job_id` from POST /documents) instead of re-parsing an upload. Returns immediately with a job id. Poll status via GET /documents/deep-transform/{job_id} and download artifacts once it succeeds. Submission is idempotent on the (document, schema) pair.
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async submitDeepTransformFrom(body: models.SubmitDeepTransformFromDocument): Promise<models.SubmitDeepTransformResponse> {
    const response = await this.http.request<models.SubmitDeepTransformResponse>("/documents/deep-transform/from-document", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get deep-transform job status
 *
 * Check status and, once succeeded, the list of downloadable artifacts.
 *
 * @param jobId - The job_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getDeepTransformStatus(jobId: string): Promise<models.DeepTransformJob> {
    const response = await this.http.request<models.DeepTransformJob>(`/documents/deep-transform/${jobId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Download a deep-transform artifact
 *
 * Download a named artifact (e.g. output.json) produced by a succeeded job. Ownership is verified against the customer header before any bytes are returned.
 *
 * @param jobId - The job_id parameter
 * @param name - The name parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async downloadDeepTransformArtifact(jobId: string, name: string): Promise<string> {
    const response = await this.http.request<string>(`/documents/deep-transform/${jobId}/artifact/${name}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Parse a document (async)
 *
 * Upload a document for asynchronous parsing. Returns a job ID to track progress.
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async parse(file: ReadableStream<Uint8Array> | Blob | File, fileName: string): Promise<models.ParseDocumentResponse> {
    const path = "/documents";
    return this.http.upload<models.ParseDocumentResponse>(path, [
      { fieldName: 'file', fileName: fileName, content: file },
    ]);
  }

/**
 * Parse a document (sync)
 *
 * Upload a document and block until parsing is complete. Returns the full parsed result.
 *
 * @param format - Result format: markdown, annotated, docling, json
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async process(file: ReadableStream<Uint8Array> | Blob | File, fileName: string, options?: { format?: string }): Promise<models.ProcessDocumentResponse> {
    const path = "/documents/process";
    const queryParams: Record<string, string | number | boolean | undefined> = {};
    if (options?.format !== undefined) {
      queryParams['format'] = options.format;
    }
    return this.http.upload<models.ProcessDocumentResponse>(path, [
      { fieldName: 'file', fileName: fileName, content: file },
    ], { params: queryParams });
  }

/**
 * Get document parsing status
 *
 * Check the status of a document parsing job, including progress statistics.
 *
 * @param jobId - The job_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getStatus(jobId: string): Promise<models.DocumentStatus> {
    const response = await this.http.request<models.DocumentStatus>(`/documents/${jobId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Get parsed document result
 *
 * Download the parsed result of a completed document parsing job.
 *
 * @param jobId - The job_id parameter
 * @param format - Result format: markdown, annotated, docling, json
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getResult(jobId: string, options?: { format?: string }): Promise<string> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      format: options?.format ?? undefined,
    };

    const response = await this.http.request<string>(`/documents/${jobId}/result`, {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * Get structured parse result
 *
 * Download the fully structured parse result (the json format): pages, typed elements, tables, chart data, chart OCR text, and bounding boxes. The response schema (StructuredDocument) is defined by the parsing engine and hoisted into this spec by the OpenAPI generator.
 *
 * @param jobId - The job_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getStructuredResult(jobId: string): Promise<models.ParseStructuredDocument> {
    const response = await this.http.request<models.ParseStructuredDocument>(`/documents/${jobId}/structured`, {
      method: "GET",
    });

    return response;
  }

/**
 * List child documents
 *
 * For container files (ZIP, TAR, EML), list the child documents extracted from the container.
 *
 * @param jobId - The job_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async listChildren(jobId: string): Promise<models.DocumentChild[]> {
    const response = await this.http.request<models.DocumentChild[]>(`/documents/${jobId}/children`, {
      method: "GET",
    });

    return response;
  }

/**
 * Stream document parsing trace
 *
 * Subscribe to real-time parsing progress via Server-Sent Events.
 *
 * @param jobId - The job_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async *streamTrace(jobId: string): AsyncIterable<Record<string, unknown>> {
    const response = await this.http.request<Response>(`/documents/${jobId}/trace`, {
      method: "GET",
      stream: true,
    });

    yield* streamSSE(response);
  }

/**
 * Transform a document using AI extraction (sync)
 *
 * Upload a document for AI-powered structured extraction and block until complete. The file is uploaded to cloud storage and processed by a system agent.
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async transform(options: { file: string | File | Blob | ReadableStream<Uint8Array>; schema: string | Record<string, unknown> | z.ZodType; model?: string; prompt?: string; promptId?: string; timeoutSeconds?: number }): Promise<models.TransformDocumentResponse> {
    const _schema = options.schema instanceof z.ZodType
      ? zodToJsonSchema(options.schema)
      : options.schema;
    const path = "/documents/transform";

    // Resolve file content
    let _fileContent: ReadableStream<Uint8Array> | Blob | File;
    let _fileName: string;
    if (typeof options.file === 'string') {
      const { createReadStream } = await import('node:fs');
      const { Readable } = await import('node:stream');
      _fileContent = Readable.toWeb(createReadStream(options.file)) as ReadableStream<Uint8Array>;
      _fileName = options.file.split('/').pop() ?? options.file;
    } else {
      _fileContent = options.file;
      _fileName = options.file instanceof File ? options.file.name : 'file';
    }

    // Build form fields from non-file smart params
    const formFields: Record<string, string> = {};
    if (typeof _schema === 'object' && _schema !== null) {
      formFields['artifact_schema'] = JSON.stringify(_schema);
    } else if (_schema != null) {
      formFields['artifact_schema'] = String(_schema);
    }
    if (options.model != null) {
      formFields['model'] = String(options.model);
    }
    if (options.prompt != null) {
      formFields['prompt'] = String(options.prompt);
    }
    if (options.promptId != null) {
      formFields['prompt_id'] = String(options.promptId);
    }
    if (options.timeoutSeconds != null) {
      formFields['timeout_seconds'] = String(options.timeoutSeconds);
    }

    return this.http.upload<models.TransformDocumentResponse>(path, [
      { fieldName: 'file', fileName: _fileName, content: _fileContent },
    ], { formFields, timeout: options.timeoutSeconds ? options.timeoutSeconds * 1000 : undefined });
  }

/**
 * Submit a document transform (async)
 *
 * Upload a document for AI-powered extraction and return immediately. Poll for completion via client.sessions.get(execution_id).
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async submitTransform(options: { file: string | File | Blob | ReadableStream<Uint8Array>; schema: string | Record<string, unknown> | z.ZodType; model?: string; prompt?: string; promptId?: string; timeoutSeconds?: number }): Promise<models.SubmitDocumentTransformResponse> {
    const _schema = options.schema instanceof z.ZodType
      ? zodToJsonSchema(options.schema)
      : options.schema;
    const path = "/documents/transform/submit";

    // Resolve file content
    let _fileContent: ReadableStream<Uint8Array> | Blob | File;
    let _fileName: string;
    if (typeof options.file === 'string') {
      const { createReadStream } = await import('node:fs');
      const { Readable } = await import('node:stream');
      _fileContent = Readable.toWeb(createReadStream(options.file)) as ReadableStream<Uint8Array>;
      _fileName = options.file.split('/').pop() ?? options.file;
    } else {
      _fileContent = options.file;
      _fileName = options.file instanceof File ? options.file.name : 'file';
    }

    // Build form fields from non-file smart params
    const formFields: Record<string, string> = {};
    if (typeof _schema === 'object' && _schema !== null) {
      formFields['artifact_schema'] = JSON.stringify(_schema);
    } else if (_schema != null) {
      formFields['artifact_schema'] = String(_schema);
    }
    if (options.model != null) {
      formFields['model'] = String(options.model);
    }
    if (options.prompt != null) {
      formFields['prompt'] = String(options.prompt);
    }
    if (options.promptId != null) {
      formFields['prompt_id'] = String(options.promptId);
    }
    if (options.timeoutSeconds != null) {
      formFields['timeout_seconds'] = String(options.timeoutSeconds);
    }

    return this.http.upload<models.SubmitDocumentTransformResponse>(path, [
      { fieldName: 'file', fileName: _fileName, content: _fileContent },
    ], { formFields, timeout: options.timeoutSeconds ? options.timeoutSeconds * 1000 : undefined });
  }

/**
 * Move documents into a datasource (async)
 *
 * Move documents (identified by their parse job IDs, e.g. the job_id returned by parseDocument) into an existing datasource or a newly created one. Returns a workflow_id to poll for completion.
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async move(body: models.MoveDocumentsRequest): Promise<models.MoveDocumentsResponse> {
    const response = await this.http.request<models.MoveDocumentsResponse>("/documents/move", {
      method: "POST",
      body,
    });

    return response;
  }

}
