/**
 * Parse and transform documents into structured data
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { streamSSE } from '../streaming.js';
import type { UploadFile } from '../upload.js';
import { z } from 'zod';
import { zodToJsonSchema } from '../schema.js';

export class DocumentsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Parse a document (async)
 *
 * Upload a document for asynchronous parsing. Returns a job ID to track progress.
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async parse(file: ReadableStream<Uint8Array> | Blob | File, fileName: string): Promise<models.ParseDocumentResponse> {
    const path = "/documents";
    return this.http.upload<models.ParseDocumentResponse>(path, [
      { fieldName: 'file', fileName: fileName, content: file },
    ]);
  }

/**
 * Parse a document (sync)
 *
 * Upload a document and block until parsing is complete. Returns the full parsed result.
 *
 * @param format - Result format: markdown, annotated, docling, json
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async process(file: ReadableStream<Uint8Array> | Blob | File, fileName: string): Promise<models.ProcessDocumentResponse> {
    const path = "/documents/process";
    return this.http.upload<models.ProcessDocumentResponse>(path, [
      { fieldName: 'file', fileName: fileName, content: file },
    ]);
  }

/**
 * Get document parsing status
 *
 * Check the status of a document parsing job, including progress statistics.
 *
 * @param jobId - The job_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getStatus(jobId: string): Promise<models.DocumentStatus> {
    const response = await this.http.request<models.DocumentStatus>(`/documents/${jobId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Get parsed document result
 *
 * Download the parsed result of a completed document parsing job.
 *
 * @param jobId - The job_id parameter
 * @param format - Result format: markdown, annotated, docling, json
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getResult(jobId: string, options?: { format?: string }): Promise<string> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      format: options?.format ?? undefined,
    };

    const response = await this.http.request<string>(`/documents/${jobId}/result`, {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * List child documents
 *
 * For container files (ZIP, TAR, EML), list the child documents extracted from the container.
 *
 * @param jobId - The job_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async listChildren(jobId: string): Promise<models.DocumentChild[]> {
    const response = await this.http.request<models.DocumentChild[]>(`/documents/${jobId}/children`, {
      method: "GET",
    });

    return response;
  }

/**
 * Stream document parsing trace
 *
 * Subscribe to real-time parsing progress via Server-Sent Events.
 *
 * @param jobId - The job_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async *streamTrace(jobId: string): AsyncIterable<models.LayoutDetectedEvent | models.TableExtractedEvent | models.OcrPageEvent | models.CompletedEvent | models.ErrorEvent> {
    const response = await this.http.request<Response>(`/documents/${jobId}/trace`, {
      method: "GET",
      stream: true,
    });

    yield* streamSSE(response);
  }

/**
 * Transform a document using AI extraction (sync)
 *
 * Submit a document for AI-powered structured extraction and block until complete. Internally orchestrates a system agent session, polls for completion, and returns the extracted data.
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async transform(options: { file: string; schema: string | Record<string, unknown> | z.ZodType; model?: string | null; prompt?: string | null; promptId?: string | null; timeoutSeconds?: number | null }): Promise<models.TransformDocumentResponse> {
    const _schema = options.schema instanceof z.ZodType
      ? zodToJsonSchema(options.schema)
      : options.schema;
    const body = {
      file: options.file,
      artifact_schema: _schema,
      model: options.model,
      prompt: options.prompt,
      prompt_id: options.promptId,
      timeout_seconds: options.timeoutSeconds,
    };

    const response = await this.http.request<models.TransformDocumentResponse>("/documents/transform", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Submit a document transform (async)
 *
 * Submit a document for AI-powered extraction and return immediately. Poll for completion via client.sessions.get(execution_id).
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async submitTransform(options: { file: string; schema: string | Record<string, unknown> | z.ZodType; model?: string | null; prompt?: string | null; promptId?: string | null; timeoutSeconds?: number | null }): Promise<models.SubmitDocumentTransformResponse> {
    const _schema = options.schema instanceof z.ZodType
      ? zodToJsonSchema(options.schema)
      : options.schema;
    const body = {
      file: options.file,
      artifact_schema: _schema,
      model: options.model,
      prompt: options.prompt,
      prompt_id: options.promptId,
      timeout_seconds: options.timeoutSeconds,
    };

    const response = await this.http.request<models.SubmitDocumentTransformResponse>("/documents/transform/submit", {
      method: "POST",
      body,
    });

    return response;
  }

}
