/**
 * Export datasources as downloadable files
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { streamSSE } from '../streaming.js';

export class DownloadsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Create Download Job (async)
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async createDownloadJob(datasourceId: string, body?: models.DownloadJobRequest | null): Promise<models.DownloadJobResponse> {
    const response = await this.http.request<models.DownloadJobResponse>(`/datasources/${datasourceId}/downloads`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Stream Download Progress
 *
 * @param datasourceId - The datasource_id parameter
 * @param jobId - The job_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async *streamDownloadProgress(datasourceId: string, jobId: string): AsyncIterable<Record<string, unknown>> {
    const response = await this.http.request<Response>(`/datasources/${datasourceId}/downloads/${jobId}/progress`, {
      method: "GET",
      stream: true,
    });

    yield* streamSSE(response);
  }

/**
 * Download File
 *
 * @param datasourceId - The datasource_id parameter
 * @param jobId - The job_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async downloadFile(datasourceId: string, jobId: string): Promise<string> {
    const response = await this.http.request<string>(`/datasources/${datasourceId}/downloads/${jobId}/file`, {
      method: "GET",
    });

    return response;
  }

/**
 * Process Download (sync)
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async processDownload(datasourceId: string, body?: models.DownloadJobRequest | null): Promise<string> {
    const response = await this.http.request<string>(`/datasources/${datasourceId}/downloads/process`, {
      method: "POST",
      body,
    });

    return response;
  }

}
