/**
 * Manage execution policies
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class ExecutionPoliciesResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Execution Policies
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async list(): Promise<models.GetExecutionPoliciesResponse> {
    const response = await this.http.request<models.GetExecutionPoliciesResponse>("/execution-policies", {
      method: "GET",
    });

    return response;
  }

/**
 * Create Execution Policy
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async create(body: models.CreateExecutionPolicyRequest): Promise<models.ExecutionPolicyResponse> {
    const response = await this.http.request<models.ExecutionPolicyResponse>("/execution-policies", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Execution Policy
 *
 * @param policyId - The policy_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async get(policyId: string): Promise<models.ExecutionPolicyResponse> {
    const response = await this.http.request<models.ExecutionPolicyResponse>(`/execution-policies/${policyId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Execution Policy
 *
 * @param policyId - The policy_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async update(policyId: string, body: models.UpdateExecutionPolicyRequest): Promise<models.ExecutionPolicyResponse> {
    const response = await this.http.request<models.ExecutionPolicyResponse>(`/execution-policies/${policyId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Execution Policy
 *
 * @param policyId - The policy_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async delete(policyId: string): Promise<void> {
    const response = await this.http.request<void>(`/execution-policies/${policyId}`, {
      method: "DELETE",
    });

    return response;
  }

}
