/**
 * Executions resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class ExecutionsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Start Blueprint Instance
 *
 * @param blueprintInstanceId - Unique identifier for the workflow instance
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async startBlueprintInstance(blueprintInstanceId: string, body?: models.StartBlueprintInstanceRequest | null): Promise<string> {
    const response = await this.http.request<string>(`/${blueprintInstanceId}/start-instance`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Cancel Blueprint Instance
 *
 * @param blueprintInstanceId - Unique identifier for the workflow instance
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async cancelBlueprintInstance(blueprintInstanceId: string): Promise<string> {
    const response = await this.http.request<string>(`/${blueprintInstanceId}/cancel-instance`, {
      method: "POST",
    });

    return response;
  }

/**
 * Send Signal
 *
 * @param blueprintInstanceId - Unique identifier for the workflow instance
 * @param signalName - Name of the signal to send
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async sendSignal(blueprintInstanceId: string, signalName: string, body?: string[] | null): Promise<string> {
    const response = await this.http.request<string>(`/${blueprintInstanceId}/signals/${signalName}`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Query Workflow
 *
 * @param blueprintInstanceId - Unique identifier for the workflow instance
 * @param queryName - Name of the query to execute
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async queryWorkflow(blueprintInstanceId: string, queryName: string, body?: string[] | null): Promise<string> {
    const response = await this.http.request<string>(`/${blueprintInstanceId}/queries/${queryName}`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Blueprint Instance Workflow Status
 *
 * @param blueprintInstanceId - Unique identifier for the workflow instance
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getBlueprintInstanceWorkflowStatus(blueprintInstanceId: string): Promise<string> {
    const response = await this.http.request<string>(`/${blueprintInstanceId}/workflow-status`, {
      method: "GET",
    });

    return response;
  }

/**
 * Send Chat Message
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async sendChatMessage(blueprintInstanceId: string, body: models.ChatMessageRequest): Promise<models.ChatMessageResponse> {
    const response = await this.http.request<models.ChatMessageResponse>(`/${blueprintInstanceId}/chat`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Send a chat message and stream the response via SSE
 *
 * Send a chat message to a running chat agent workflow and stream the response as Server-Sent Events.
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async sendChatMessageStreamBlueprintInstanceIdChatStreamPost(blueprintInstanceId: string, body: models.ChatMessageRequest): Promise<string> {
    const response = await this.http.request<string>(`/${blueprintInstanceId}/chat/stream`, {
      method: "POST",
      body,
    });

    return response;
  }

}
