/**
 * Upload and manage content files
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';
import { streamSSE } from '../streaming.js';
import type { UploadFile } from '../upload.js';

export class FileUploadsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Content
 *
 * @param datasourceId - The datasource_id parameter
 * @param prefix - Filter content by path prefix
 * @param continuationToken - Token for pagination
 * @param limit - Maximum items to return
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listContent(datasourceId: string, options?: { prefix?: string | null; continuationToken?: string | null; limit?: number }): AsyncIterable<models.ContentItem> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      prefix: options?.prefix ?? undefined,
      continuation_token: options?.continuationToken ?? undefined,
      limit: options?.limit ?? undefined,
    };

    yield* paginate<models.ContentItem>(async (cursor) => {
      const response = await this.http.request<models.ListContentResponse>(`/datasources/${datasourceId}/content`, {
        method: "GET",
        params: {
          ...queryParams,
          continuation_token: cursor,
        },
      });
      return {
        items: response.items ?? [],
      };
    });
  }

/**
 * Upload Content (async)
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async uploadContent(datasourceId: string, files: ReadableStream<Uint8Array> | Blob | File, filesName: string): Promise<models.UploadContentResponse> {
    const path = `/datasources/${datasourceId}/content`;
    return this.http.upload<models.UploadContentResponse>(path, [
      { fieldName: 'files', fileName: filesName, content: files },
    ]);
  }

/**
 * Upload Content (sync)
 *
 * @param datasourceId - The datasource_id parameter
 * @param triggerIngest - Start ingestion after upload completes. Returns ingest_url to poll for status.
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async uploadAndListContent(datasourceId: string, files: ReadableStream<Uint8Array> | Blob | File, filesName: string, options?: { triggerIngest?: boolean }): Promise<models.FileUploadSyncResponse> {
    const path = `/datasources/${datasourceId}/content/process`;
    const queryParams: Record<string, string | number | boolean | undefined> = {};
    if (options?.triggerIngest !== undefined) {
      queryParams['trigger_ingest'] = options.triggerIngest;
    }
    return this.http.upload<models.FileUploadSyncResponse>(path, [
      { fieldName: 'files', fileName: filesName, content: files },
    ], { params: queryParams });
  }

/**
 * Stream Upload Progress
 *
 * @param uploadId - The upload_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async *streamUploadProgress(uploadId: string): AsyncIterable<models.ConnectedEvent | Record<string, unknown>> {
    const response = await this.http.request<Response>(`/datasources/uploads/${uploadId}/progress`, {
      method: "GET",
      stream: true,
    });

    yield* streamSSE(response);
  }

}
