/**
 * Upload and manage content files
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';
import { streamSSE } from '../streaming.js';
import type { UploadFile } from '../upload.js';

export class FileUploadsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Upload Content (async)
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async uploadContent(files: ReadableStream<Uint8Array> | Blob | File, filesName: string, options?: { datasourceId?: string; name?: string; description?: string; metadataConfig?: models.MetadataConfigRequest }): Promise<models.UploadContentResponse> {
    const path = "/datasources/uploads";
    const formFields: Record<string, string> = {};
    if (options?.datasourceId !== undefined) {
      formFields['datasource_id'] = String(options.datasourceId);
    }
    if (options?.name !== undefined) {
      formFields['name'] = String(options.name);
    }
    if (options?.description !== undefined) {
      formFields['description'] = String(options.description);
    }
    if (options?.metadataConfig !== undefined) {
      formFields['metadata_config'] = String(options.metadataConfig);
    }
    return this.http.upload<models.UploadContentResponse>(path, [
      { fieldName: 'files', fileName: filesName, content: files },
    ], { formFields });
  }

/**
 * Upload Content (sync)
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async uploadAndListContent(files: ReadableStream<Uint8Array> | Blob | File, filesName: string, options?: { datasourceId?: string; name?: string; description?: string; metadataConfig?: models.MetadataConfigRequest; triggerIngest?: boolean }): Promise<models.FileUploadSyncResponse> {
    const path = "/datasources/uploads/process";
    const formFields: Record<string, string> = {};
    if (options?.datasourceId !== undefined) {
      formFields['datasource_id'] = String(options.datasourceId);
    }
    if (options?.name !== undefined) {
      formFields['name'] = String(options.name);
    }
    if (options?.description !== undefined) {
      formFields['description'] = String(options.description);
    }
    if (options?.metadataConfig !== undefined) {
      formFields['metadata_config'] = String(options.metadataConfig);
    }
    if (options?.triggerIngest !== undefined) {
      formFields['trigger_ingest'] = String(options.triggerIngest);
    }
    return this.http.upload<models.FileUploadSyncResponse>(path, [
      { fieldName: 'files', fileName: filesName, content: files },
    ], { formFields });
  }

/**
 * Stream Upload Progress
 *
 * @param uploadId - The upload_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async *streamUploadProgress(uploadId: string): AsyncIterable<models.ConnectedEvent | models.ProgressEvent | models.StreamCompleteEvent | models.ErrorEvent> {
    const response = await this.http.request<Response>(`/datasources/uploads/${uploadId}/progress`, {
      method: "GET",
      stream: true,
    });

    yield* streamSSE(response);
  }

/**
 * List Content
 *
 * @param datasourceId - The datasource_id parameter
 * @param prefix - Filter content by path prefix
 * @param continuationToken - Token for pagination
 * @param limit - Maximum items to return
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listContent(datasourceId: string, options?: { prefix?: string | null; continuationToken?: string | null; limit?: number }): AsyncIterable<models.ContentItem> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      prefix: options?.prefix ?? undefined,
      continuation_token: options?.continuationToken ?? undefined,
      limit: options?.limit ?? undefined,
    };

    yield* paginate<models.ContentItem>(async (cursor) => {
      const response = await this.http.request<models.ListContentResponse>(`/datasources/${datasourceId}/content`, {
        method: "GET",
        params: {
          ...queryParams,
          continuation_token: cursor,
        },
      });
      return {
        items: response.items ?? [],
      };
    });
  }

}
