/**
 * Resource exports.
 *
 * Generated by Forge SDK Generator.
 */

export { ConfidenceScoringResource } from './confidence-scoring.js';
export { ContentResource } from './content.js';
export { DataElementMetadataResource } from './data-element-metadata.js';
export { DataElementsResource } from './data-elements.js';
export { DatasourcesResource } from './datasources.js';
export { DocumentsResource } from './documents.js';
export { MetadataConfigurationResource } from './metadata-configuration.js';
export { MetadataModelCatalogResource } from './metadata-model-catalog.js';
export { TagDescriptionsResource } from './tag-descriptions.js';
