/**
 * Ingest resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class IngestResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Trigger Ingest
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async triggerIngest(datasourceId: string): Promise<string> {
    const response = await this.http.request<string>(`/datasources/${datasourceId}/trigger-ingest`, {
      method: "POST",
    });

    return response;
  }

/**
 * Get Ingest Status
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getIngestStatus(datasourceId: string): Promise<models.IngestStatusResponse> {
    const response = await this.http.request<models.IngestStatusResponse>(`/datasources/${datasourceId}/ingest-status`, {
      method: "GET",
    });

    return response;
  }

}
