/**
 * Instances resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class InstancesResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get All Blueprint Instances
 *
 * @param includeChildren - The include_children parameter
 * @param includeActivities - The include_activities parameter
 * @param includeEvents - The include_events parameter
 * @param offset - Number of items to skip
 * @param limit - Maximum number of items to return
 * @param sortBy - Field to sort by
 * @param sortOrder - Sort order (asc or desc)
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getAllBlueprintInstances(options?: { includeChildren?: boolean; includeActivities?: boolean; includeEvents?: boolean; offset?: number; limit?: number; sortBy?: string | null; sortOrder?: string | null }): Promise<models.GetBlueprintInstancesResponse> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      include_children: options?.includeChildren ?? undefined,
      include_activities: options?.includeActivities ?? undefined,
      include_events: options?.includeEvents ?? undefined,
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
      sort_by: options?.sortBy ?? undefined,
      sort_order: options?.sortOrder ?? undefined,
    };

    const response = await this.http.request<models.GetBlueprintInstancesResponse>("/blueprint-instance/", {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * Add Blueprint Instance
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async addBlueprintInstance(body: models.AddBlueprintInstanceRequest): Promise<models.AddBlueprintInstanceResponse> {
    const response = await this.http.request<models.AddBlueprintInstanceResponse>("/blueprint-instance/", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Blueprint Instance
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param includeChildren - The include_children parameter
 * @param includeActivities - The include_activities parameter
 * @param includeEvents - The include_events parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getBlueprintInstance(blueprintInstanceId: string, options?: { includeChildren?: boolean; includeActivities?: boolean; includeEvents?: boolean }): Promise<models.GetBlueprintInstancesResponse> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      include_children: options?.includeChildren ?? undefined,
      include_activities: options?.includeActivities ?? undefined,
      include_events: options?.includeEvents ?? undefined,
    };

    const response = await this.http.request<models.GetBlueprintInstancesResponse>(`/blueprint-instance/${blueprintInstanceId}`, {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * Delete Blueprint Instance
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async deleteBlueprintInstance(blueprintInstanceId: string): Promise<void> {
    const response = await this.http.request<void>(`/blueprint-instance/${blueprintInstanceId}`, {
      method: "DELETE",
    });

    return response;
  }

/**
 * Update Blueprint Instance Status
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param updatedStatusValue - The updated_status_value parameter
 * @param workflowRunId - The workflow_run_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async updateBlueprintInstanceStatus(blueprintInstanceId: string, updatedStatusValue: models.BlueprintInstanceStatus, options?: { workflowRunId?: string | null }): Promise<void> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      updated_status_value: updatedStatusValue,
      workflow_run_id: options?.workflowRunId ?? undefined,
    };

    const response = await this.http.request<void>(`/blueprint-instance/${blueprintInstanceId}/status`, {
      method: "PUT",
      params: queryParams,
    });

    return response;
  }

/**
 * Complete a Blueprint Instance
 *
 * This endpoint is used to mark a Blueprint Instance as completed. It will update the status of the Blueprint Instance to 'COMPLETED' and log the completion event.
 *
 * @param blueprintInstanceId - Unique identifier for the workflow instance
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async completeBlueprintInstance(blueprintInstanceId: string, body?: models.CompleteBlueprintInstanceRequest | null): Promise<string> {
    const response = await this.http.request<string>(`/blueprint-instance/${blueprintInstanceId}/complete-instance`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Fail a Blueprint Instance
 *
 * This endpoint is used to mark a Blueprint Instance as failed. It will update the status of the Blueprint Instance to 'FAILED' and log the failure event.
 *
 * @param blueprintInstanceId - Unique identifier for the workflow instance
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async failBlueprintInstance(blueprintInstanceId: string, body: models.FailBlueprintInstanceRequest): Promise<string> {
    const response = await this.http.request<string>(`/blueprint-instance/${blueprintInstanceId}/fail-instance`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Add Activity By Blueprint Instance
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async addActivityByBlueprintInstance(blueprintInstanceId: string, body: models.AddActivityRequest): Promise<models.AddActivityResponse> {
    const response = await this.http.request<models.AddActivityResponse>(`/blueprint-instance/${blueprintInstanceId}/activity`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Activity By Blueprint Instance
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param activityId - The activity_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getActivityByBlueprintInstance(blueprintInstanceId: string, activityId: string): Promise<models.GetActivitiesResponse> {
    const response = await this.http.request<models.GetActivitiesResponse>(`/blueprint-instance/${blueprintInstanceId}/activity/${activityId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Get Activities By Blueprint Instance
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param offset - Number of items to skip
 * @param limit - Maximum number of items to return
 * @param sortBy - Field to sort by
 * @param sortOrder - Sort order (asc or desc)
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getActivitiesByBlueprintInstance(blueprintInstanceId: string, options?: { offset?: number; limit?: number; sortBy?: string | null; sortOrder?: string | null }): Promise<models.GetActivitiesResponse> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
      sort_by: options?.sortBy ?? undefined,
      sort_order: options?.sortOrder ?? undefined,
    };

    const response = await this.http.request<models.GetActivitiesResponse>(`/blueprint-instance/${blueprintInstanceId}/activities`, {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * Update Activity Status
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param activityId - The activity_id parameter
 * @param updatedStatusValue - The updated_status_value parameter
 *
 * @throws {ApiError} If the request fails
 */
  async updateActivityStatus(blueprintInstanceId: string, activityId: string, updatedStatusValue: models.ActivityStatus): Promise<void> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      updated_status_value: updatedStatusValue,
    };

    const response = await this.http.request<void>(`/blueprint-instance/${blueprintInstanceId}/activity/${activityId}/status`, {
      method: "PUT",
      params: queryParams,
    });

    return response;
  }

/**
 * Get Event By Blueprint Instance
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param eventId - The event_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getEventByBlueprintInstance(blueprintInstanceId: string, eventId: string): Promise<models.GetEventsResponse> {
    const response = await this.http.request<models.GetEventsResponse>(`/blueprint-instance/${blueprintInstanceId}/event/${eventId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Create Event By Blueprint Instance Id
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async createEventByBlueprintInstanceId(blueprintInstanceId: string, body: models.CustomEventRequest): Promise<models.AddEventResponse> {
    const response = await this.http.request<models.AddEventResponse>(`/blueprint-instance/${blueprintInstanceId}/event`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Events By Blueprint Instance
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param offset - Number of items to skip
 * @param limit - Maximum number of items to return
 * @param sortBy - Field to sort by
 * @param sortOrder - Sort order (asc or desc)
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getEventsByBlueprintInstance(blueprintInstanceId: string, options?: { offset?: number; limit?: number; sortBy?: string | null; sortOrder?: string | null }): Promise<models.GetEventsResponse> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      offset: options?.offset ?? undefined,
      limit: options?.limit ?? undefined,
      sort_by: options?.sortBy ?? undefined,
      sort_order: options?.sortOrder ?? undefined,
    };

    const response = await this.http.request<models.GetEventsResponse>(`/blueprint-instance/${blueprintInstanceId}/events`, {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

}
