/**
 * MetadataConfiguration resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class MetadataConfigurationResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get Metadata Config
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getMetadataConfig(datasourceId: string): Promise<models.MetadataConfigResponse> {
    const response = await this.http.request<models.MetadataConfigResponse>(`/v2/datasources/${datasourceId}/metadata-config`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Metadata Config
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateMetadataConfig(datasourceId: string, body: models.MetadataConfigRequest): Promise<models.MetadataConfigResponse> {
    const response = await this.http.request<models.MetadataConfigResponse>(`/v2/datasources/${datasourceId}/metadata-config`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Reprocess Metadata
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async reprocessMetadata(datasourceId: string): Promise<string> {
    const response = await this.http.request<string>(`/v2/datasources/${datasourceId}/reprocess-metadata`, {
      method: "POST",
    });

    return response;
  }

/**
 * Get Reprocess Metadata Status
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getReprocessMetadataStatus(datasourceId: string): Promise<string> {
    const response = await this.http.request<string>(`/v2/datasources/${datasourceId}/reprocess-metadata/status`, {
      method: "GET",
    });

    return response;
  }

}
