/**
 * MetadataModelCatalog resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';

export class MetadataModelCatalogResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Metadata Model Catalog
 *
 * @param scope - The scope parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listMetadataModelCatalog(options?: { scope?: string | null }): AsyncIterable<models.MetadataModelCatalogEntry> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      scope: options?.scope ?? undefined,
    };

    yield* paginate<models.MetadataModelCatalogEntry>(async (cursor) => {
      const response = await this.http.request<models.ListMetadataModelCatalogResponse>("/v2/metadata-model-catalog", {
        method: "GET",
        params: {
          ...queryParams,
          offset: cursor,
        },
      });
      return {
        items: response.models ?? [],
      };
    });
  }

/**
 * Get Metadata Model Catalog Entry
 *
 * @param modelId - The model_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getMetadataModelCatalogEntry(modelId: string): Promise<models.MetadataModelCatalogEntry> {
    const response = await this.http.request<models.MetadataModelCatalogEntry>(`/v2/metadata-model-catalog/${modelId}`, {
      method: "GET",
    });

    return response;
  }

}
