/**
 * Manage reusable prompt templates
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class PromptsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Prompts
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async listPrompts(): Promise<models.PromptListResponse> {
    const response = await this.http.request<models.PromptListResponse>("/prompts/", {
      method: "GET",
    });

    return response;
  }

/**
 * Create Prompt
 *
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async createPrompt(body: models.CreateAgentPromptRequest): Promise<models.CreatePromptResponse> {
    const response = await this.http.request<models.CreatePromptResponse>("/prompts/", {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Get Prompt
 *
 * @param promptId - The prompt_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getPrompt(promptId: string): Promise<models.PromptResponse> {
    const response = await this.http.request<models.PromptResponse>(`/prompts/${promptId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Prompt
 *
 * @param promptId - The prompt_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updatePrompt(promptId: string, body: models.UpdateAgentPromptRequest): Promise<models.UpdatePromptResponse> {
    const response = await this.http.request<models.UpdatePromptResponse>(`/prompts/${promptId}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Delete Prompt
 *
 * @param promptId - The prompt_id parameter
 *
 * @throws {ApiError} If the request fails
 */
  async deletePrompt(promptId: string): Promise<void> {
    const response = await this.http.request<void>(`/prompts/${promptId}`, {
      method: "DELETE",
    });

    return response;
  }

}
