/**
 * Interact with agent sessions via chat
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class SessionsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Send Chat Message
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async sendChatMessage(blueprintInstanceId: string, body: models.ChatMessageRequest): Promise<models.ChatMessageResponse> {
    const response = await this.http.request<models.ChatMessageResponse>(`/${blueprintInstanceId}/chat`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Send a chat message and stream the response via SSE
 *
 * Send a chat message to a running chat agent workflow and stream the response as Server-Sent Events.
 *
 * @param blueprintInstanceId - The blueprint_instance_id parameter
 * @param body - Request body
 *
 * @throws {ApiError} If the request fails
 */
  async sendChatMessageStream(blueprintInstanceId: string, body: models.ChatMessageRequest): Promise<void> {
    const response = await this.http.request<void>(`/${blueprintInstanceId}/chat/stream`, {
      method: "POST",
      body,
    });

    return response;
  }

}
