/**
 * Interact with agent sessions via chat
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { streamSSE } from '../streaming.js';

export class SessionsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get Session
 *
 * @param sessionId - The session_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getSession(sessionId: string): Promise<models.AgentExecutionDetailsResponse> {
    const response = await this.http.request<models.AgentExecutionDetailsResponse>(`/sessions/${sessionId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Get Session Messages
 *
 * @param sessionId - The session_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getSessionMessages(sessionId: string): Promise<models.SessionMessagesResponse> {
    const response = await this.http.request<models.SessionMessagesResponse>(`/sessions/${sessionId}/messages`, {
      method: "GET",
    });

    return response;
  }

/**
 * Send Chat Message
 *
 * @param sessionId - The session_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async sendChatMessage(sessionId: string, body: models.ChatMessageRequest): Promise<models.ChatMessageResponse> {
    const response = await this.http.request<models.ChatMessageResponse>(`/sessions/${sessionId}/chat`, {
      method: "POST",
      body,
    });

    return response;
  }

/**
 * Send a chat message and stream the response via SSE
 *
 * @param sessionId - The session_id parameter
 * @param body - Request body
 *
 * @throws {ApiError} If the request fails
 */
  async *sendChatMessageStream(sessionId: string, body: models.ChatMessageRequest): AsyncIterable<Record<string, unknown>> {
    const response = await this.http.request<Response>(`/sessions/${sessionId}/chat/stream`, {
      method: "POST",
      body,
      stream: true,
    });

    yield* streamSSE(response);
  }

}
