/**
 * View session details across agents
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class SessionsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * Get Session
 *
 * @param sessionId - The session_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getSession(sessionId: string): Promise<models.AgentExecutionDetailsResponse> {
    const response = await this.http.request<models.AgentExecutionDetailsResponse>(`/sessions/${sessionId}`, {
      method: "GET",
    });

    return response;
  }

/**
 * Get Session Messages
 *
 * @param sessionId - The session_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async getSessionMessages(sessionId: string): Promise<models.SessionMessagesResponse> {
    const response = await this.http.request<models.SessionMessagesResponse>(`/sessions/${sessionId}/messages`, {
      method: "GET",
    });

    return response;
  }

}
