/**
 * Manage table and column descriptions for AI context
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';

export class TableDescriptionsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Tables
 *
 * @param datasourceId - The datasource_id parameter
 * @param includeColumns - Include columns for each table
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async listTables(datasourceId: string, options?: { includeColumns?: boolean }): Promise<models.TagTable[]> {
    const queryParams: Record<string, string | number | boolean | undefined> = {
      include_columns: options?.includeColumns ?? undefined,
    };

    const response = await this.http.request<models.TagTable[]>(`/datasources/${datasourceId}/tables`, {
      method: "GET",
      params: queryParams,
    });

    return response;
  }

/**
 * Update Table Descriptions
 *
 * @param datasourceId - The datasource_id parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateTableDescriptions(datasourceId: string, body: models.TagTableUpdateItem[]): Promise<models.TagTable[]> {
    const response = await this.http.request<models.TagTable[]>(`/datasources/${datasourceId}/tables`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * List Columns
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async listColumns(datasourceId: string, tableName: string): Promise<models.TagColumn[]> {
    const response = await this.http.request<models.TagColumn[]>(`/datasources/${datasourceId}/tables/${tableName}/columns`, {
      method: "GET",
    });

    return response;
  }

/**
 * Update Column Descriptions
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateColumnDescriptions(datasourceId: string, tableName: string, body: models.TagColumnUpdateItem[]): Promise<models.TagColumn[]> {
    const response = await this.http.request<models.TagColumn[]>(`/datasources/${datasourceId}/tables/${tableName}/columns`, {
      method: "PUT",
      body,
    });

    return response;
  }

}
