/**
 * TagDescriptions resource
 *
 * Generated by Forge SDK Generator.
 */

import type { HttpClient } from '../http.js';
import * as models from '../models.js';
import { paginate } from '../pagination.js';

export class TagDescriptionsResource {
  constructor(private readonly http: HttpClient) {}

/**
 * List Tag Tables
 *
 * @param datasourceId - The datasource_id parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listTagTables(datasourceId: string): AsyncIterable<models.TagTable> {
    yield* paginate<models.TagTable>(async (cursor) => {
      const response = await this.http.request<models.TagTable[]>(`/v2/datasources/${datasourceId}/tag-tables`, {
        method: "GET",
        params: {
          offset: cursor,
        },
      });
      return {
        items: response ?? [],
      };
    });
  }

/**
 * List Tag Columns
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async *listTagColumns(datasourceId: string, tableName: string): AsyncIterable<models.TagColumn> {
    yield* paginate<models.TagColumn>(async (cursor) => {
      const response = await this.http.request<models.TagColumn[]>(`/v2/datasources/${datasourceId}/tag-tables/${tableName}/columns`, {
        method: "GET",
        params: {
          offset: cursor,
        },
      });
      return {
        items: response ?? [],
      };
    });
  }

/**
 * Update Tag Table Description
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateTagTableDescription(datasourceId: string, tableName: string, body: models.UpdateTagDescriptionRequest): Promise<models.TagTable> {
    const response = await this.http.request<models.TagTable>(`/v2/datasources/${datasourceId}/tag-tables/${tableName}`, {
      method: "PUT",
      body,
    });

    return response;
  }

/**
 * Update Tag Column Description
 *
 * @param datasourceId - The datasource_id parameter
 * @param tableName - The table_name parameter
 * @param columnName - The column_name parameter
 * @param body - Request body
 *
 * @returns Successful Response
 *
 * @throws {ApiError} If the request fails
 */
  async updateTagColumnDescription(datasourceId: string, tableName: string, columnName: string, body: models.UpdateTagDescriptionRequest): Promise<models.TagColumn> {
    const response = await this.http.request<models.TagColumn>(`/v2/datasources/${datasourceId}/tag-tables/${tableName}/columns/${columnName}`, {
      method: "PUT",
      body,
    });

    return response;
  }

}
