/**
 * Artifact Schema Helpers
 *
 * Converts Zod schemas into CreateAgentArtifactRequest-shaped objects,
 * with format-aware schema generation for JSON, CSV, Markdown, YAML, and more.
 *
 * Generated by Forge SDK Generator.
 */

import { z } from "zod";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type ArtifactTypeString =
  | "json"
  | "csv"
  | "markdown"
  | "yaml"
  | "text"
  | "html"
  | "pdf";

type StorageStrategyString = "inline" | "gcs" | "auto";

interface ArtifactSchemaOptions {
  displayName: string;
  type?: ArtifactTypeString;
  description?: string;
  required?: boolean;
  maxSizeBytes?: number;
  storageStrategy?: StorageStrategyString;
}

// ---------------------------------------------------------------------------
// Zod type introspection helpers
// ---------------------------------------------------------------------------

function unwrapZodType(zodType: z.ZodTypeAny): z.ZodTypeAny {
  if (zodType instanceof z.ZodOptional || zodType instanceof z.ZodNullable) {
    return unwrapZodType((zodType as any)._def.innerType);
  }
  if (zodType instanceof z.ZodDefault) {
    return unwrapZodType((zodType as any)._def.innerType);
  }
  return zodType;
}

function isOptionalType(zodType: z.ZodTypeAny): boolean {
  if (zodType instanceof z.ZodOptional || zodType instanceof z.ZodNullable) {
    return true;
  }
  if (zodType instanceof z.ZodDefault) {
    return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// JSON Schema generation from Zod
// ---------------------------------------------------------------------------

function zodTypeToJsonSchema(zodType: z.ZodTypeAny): Record<string, unknown> {
  const inner = unwrapZodType(zodType);

  if (inner instanceof z.ZodString) {
    return { type: "string" };
  }
  if (inner instanceof z.ZodNumber) {
    const checks = (inner as any)._def.checks as
      | Array<{ kind: string }>
      | undefined;
    if (checks?.some((c) => c.kind === "int")) {
      return { type: "integer" };
    }
    return { type: "number" };
  }
  if (inner instanceof z.ZodBoolean) {
    return { type: "boolean" };
  }
  if (inner instanceof z.ZodDate) {
    return { type: "string", format: "date-time" };
  }
  if (inner instanceof z.ZodEnum) {
    const values = (inner as any)._def.values as string[];
    return { type: "string", enum: values };
  }
  if (inner instanceof z.ZodArray) {
    const itemType = (inner as any)._def.type as z.ZodTypeAny;
    return { type: "array", items: zodTypeToJsonSchema(itemType) };
  }
  if (inner instanceof z.ZodObject) {
    return zodObjectToJsonSchema(inner);
  }

  // Best-effort fallback for unknown types
  return { type: "string" };
}

function zodObjectToJsonSchema(
  schema: z.ZodObject<any>
): Record<string, unknown> {
  const shape = schema.shape as Record<string, z.ZodTypeAny>;
  const properties: Record<string, unknown> = {};
  const requiredFields: string[] = [];

  for (const [name, zodType] of Object.entries(shape)) {
    const jsonType = zodTypeToJsonSchema(zodType);
    if (zodType.description) {
      (jsonType as any).description = zodType.description;
    }
    properties[name] = jsonType;

    if (!isOptionalType(zodType)) {
      requiredFields.push(name);
    }
  }

  const result: Record<string, unknown> = {
    type: "object",
    properties,
  };

  if (schema.description) {
    result.title = schema.description;
  }

  if (requiredFields.length > 0) {
    result.required = requiredFields;
  }

  return result;
}

// ---------------------------------------------------------------------------
// CSV column generation from Zod
// ---------------------------------------------------------------------------

interface CsvColumn {
  name: string;
  type: string;
  description: string;
}

function zodToCsvType(zodType: z.ZodTypeAny): string {
  const inner = unwrapZodType(zodType);
  if (inner instanceof z.ZodString) return "string";
  if (inner instanceof z.ZodNumber) {
    const checks = (inner as any)._def.checks as
      | Array<{ kind: string }>
      | undefined;
    if (checks?.some((c) => c.kind === "int")) return "integer";
    return "number";
  }
  if (inner instanceof z.ZodBoolean) return "boolean";
  return "string";
}

function zodToCsvColumns(
  schema: z.ZodObject<any>,
  prefix: string = "",
  depth: number = 0
): CsvColumn[] {
  const shape = schema.shape as Record<string, z.ZodTypeAny>;
  const columns: CsvColumn[] = [];

  for (const [name, zodType] of Object.entries(shape)) {
    const fullName = prefix ? `${prefix}.${name}` : name;
    const desc = zodType.description ?? name.replace(/_/g, " ");
    const inner = unwrapZodType(zodType);

    if (inner instanceof z.ZodObject && depth < 2) {
      columns.push(...zodToCsvColumns(inner, fullName, depth + 1));
    } else {
      columns.push({
        name: fullName,
        type: zodToCsvType(zodType),
        description: desc,
      });
    }
  }

  return columns;
}

// ---------------------------------------------------------------------------
// Markdown section generation from Zod
// ---------------------------------------------------------------------------

interface MarkdownSection {
  heading: string;
  description: string;
}

function zodToMarkdownSections(
  schema: z.ZodObject<any>,
  level: number = 2
): MarkdownSection[] {
  const shape = schema.shape as Record<string, z.ZodTypeAny>;
  const sections: MarkdownSection[] = [];

  for (const [name, zodType] of Object.entries(shape)) {
    const desc = zodType.description ?? name.replace(/_/g, " ");
    const headingPrefix = "#".repeat(level);
    const headingName = name
      .replace(/_/g, " ")
      .replace(/\b\w/g, (c) => c.toUpperCase());
    const inner = unwrapZodType(zodType);

    sections.push({
      heading: `${headingPrefix} ${headingName}`,
      description: desc,
    });

    if (inner instanceof z.ZodObject && level < 4) {
      sections.push(...zodToMarkdownSections(inner, level + 1));
    }
  }

  return sections;
}

// ---------------------------------------------------------------------------
// Schema builder
// ---------------------------------------------------------------------------

const FREEFORM_TYPES = new Set(["markdown", "text", "html", "pdf"]);
const SCHEMA_REQUIRED_TYPES = new Set(["json", "csv", "yaml"]);

function buildSchemaDef(
  schema: z.ZodObject<any> | null,
  type: string
): string {
  if (schema === null) {
    if (SCHEMA_REQUIRED_TYPES.has(type)) {
      throw new Error(
        `A Zod schema is required for artifact type '${type}'. ` +
          `Only markdown, text, html, and pdf support freeform (no schema).`
      );
    }
    return JSON.stringify({ freeform: true, sections: [] });
  }

  if (type === "json" || type === "yaml") {
    return JSON.stringify(zodObjectToJsonSchema(schema));
  } else if (type === "csv") {
    return JSON.stringify(zodToCsvColumns(schema));
  } else if (type === "markdown") {
    return JSON.stringify({ sections: zodToMarkdownSections(schema) });
  } else {
    // text, html, pdf — use JSON Schema as validation hints
    return JSON.stringify(zodObjectToJsonSchema(schema));
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Convert a Zod schema into a CreateAgentArtifactRequest-shaped object.
 *
 * @example
 * ```typescript
 * import { z } from "zod";
 * import { artifactSchema } from "meibel";
 *
 * const InvoiceOutput = z.object({
 *   vendorName: z.string().describe("Name of the vendor"),
 *   totalAmount: z.number().describe("Invoice total"),
 *   lineItems: z.array(z.string()).describe("Extracted line items"),
 * });
 *
 * const request = artifactSchema(InvoiceOutput, {
 *   displayName: "Invoice Output",
 *   type: "json",
 *   description: "Structured invoice data",
 * });
 *
 * await client.artifactSchemas.create(request);
 * ```
 *
 * For freeform markdown (no schema):
 * ```typescript
 * const request = artifactSchema(null, {
 *   displayName: "Exploration Report",
 *   type: "markdown",
 * });
 * ```
 *
 * @param schema A Zod object schema, or null for freeform types.
 * @param options Configuration for the artifact schema request.
 * @returns An object matching the CreateAgentArtifactRequest shape.
 */
export function artifactSchema(
  schema: z.ZodObject<any> | null,
  options: ArtifactSchemaOptions
): Record<string, unknown> {
  const type = options.type ?? "json";
  const schemaDef = buildSchemaDef(schema, type);

  const result: Record<string, unknown> = {
    displayName: options.displayName,
    type,
    schemaDef,
  };

  if (options.description !== undefined) {
    result.description = options.description;
  }
  if (options.required !== undefined) {
    result.required = options.required;
  }
  if (options.maxSizeBytes !== undefined) {
    result.maxSizeBytes = options.maxSizeBytes;
  }
  if (options.storageStrategy !== undefined) {
    result.storageStrategy = options.storageStrategy;
  }

  return result;
}
