/**
 * meibel client.
 *
 * Generated by Forge SDK Generator.
 */

import { HttpClient, type HttpClientOptions } from './http.js';
import { BlueprintsResource } from './resources/blueprints.js';
import { ExecutionsResource } from './resources/executions.js';
import { InstancesResource } from './resources/instances.js';
import { DatasourcesResource } from './resources/datasources.js';
import { ContentResource } from './resources/content.js';
import { DataelementsResource } from './resources/dataelements.js';
import { RagResource } from './resources/rag.js';
import { TagResource } from './resources/tag.js';

export interface ClientOptions extends HttpClientOptions {
  /** API key for authentication */
  apiKey?: string;
  /** Bearer token for authentication */
  bearerToken?: string;
}

export class MeibelClient {
  private readonly http: HttpClient;

  public readonly blueprints: BlueprintsResource;
  public readonly datasources: DatasourcesResource;

  constructor(options: ClientOptions = {}) {
    const baseUrl = options.baseUrl ?? "https://api.meibel.ai/v1";
    const headers: Record<string, string> = { ...options.headers };

    if (options.apiKey) {
      headers["Meibel-API-Key"] = options.apiKey;
    }
    if (options.bearerToken) {
      headers["Authorization"] = `Bearer ${options.bearerToken}`;
    }

    this.http = new HttpClient({
      ...options,
      baseUrl,
      headers,
    });

    this.blueprints = new BlueprintsResource(this.http);
    this.datasources = new DatasourcesResource(this.http);
  }
}
