/**
 * meibel client.
 *
 * Generated by Forge SDK Generator.
 */

import { HttpClient, type HttpClientOptions } from './http.js';
import { ConfidenceScoringResource } from './resources/confidence-scoring.js';
import { ContentResource } from './resources/content.js';
import { DataElementMetadataResource } from './resources/data-element-metadata.js';
import { DataElementsResource } from './resources/data-elements.js';
import { DatasourcesResource } from './resources/datasources.js';
import { DocumentsResource } from './resources/documents.js';
import { MetadataConfigurationResource } from './resources/metadata-configuration.js';
import { MetadataModelCatalogResource } from './resources/metadata-model-catalog.js';
import { TagDescriptionsResource } from './resources/tag-descriptions.js';

export interface ClientOptions extends HttpClientOptions {
  /** API key for authentication */
  apiKey?: string;
  /** Bearer token for authentication */
  bearerToken?: string;
}

export class MeibelClient {
  private readonly http: HttpClient;

  public readonly confidenceScoring: ConfidenceScoringResource;
  public readonly content: ContentResource;
  public readonly dataElementMetadata: DataElementMetadataResource;
  public readonly dataElements: DataElementsResource;
  public readonly datasources: DatasourcesResource;
  public readonly documents: DocumentsResource;
  public readonly metadataConfiguration: MetadataConfigurationResource;
  public readonly metadataModelCatalog: MetadataModelCatalogResource;
  public readonly tagDescriptions: TagDescriptionsResource;

  constructor(options: ClientOptions = {}) {
    const baseUrl = options.baseUrl ?? "https://api.meibel.ai/v2";
    const headers: Record<string, string> = { ...options.headers };

    if (options.apiKey) {
      headers["Meibel-API-Key"] = options.apiKey;
    }
    if (options.bearerToken) {
      headers["Authorization"] = `Bearer ${options.bearerToken}`;
    }

    this.http = new HttpClient({
      ...options,
      baseUrl,
      headers,
    });

    this.confidenceScoring = new ConfidenceScoringResource(this.http);
    this.content = new ContentResource(this.http);
    this.dataElementMetadata = new DataElementMetadataResource(this.http);
    this.dataElements = new DataElementsResource(this.http);
    this.datasources = new DatasourcesResource(this.http);
    this.documents = new DocumentsResource(this.http);
    this.metadataConfiguration = new MetadataConfigurationResource(this.http);
    this.metadataModelCatalog = new MetadataModelCatalogResource(this.http);
    this.tagDescriptions = new TagDescriptionsResource(this.http);
  }
}
