/**
 * meibel-ai-api client.
 *
 * Generated by Forge SDK Generator.
 */

import { HttpClient, type HttpClientOptions } from './http.js';
import { AgentsResource } from './resources/agents.js';
import { AgentsSessionsResource } from './resources/agents-sessions.js';
import { ArtifactSchemasResource } from './resources/artifact-schemas.js';
import { ConfidenceScoringResource } from './resources/confidence-scoring.js';
import { DatasourcesResource } from './resources/datasources.js';
import { ContentResource } from './resources/content.js';
import { DataElementsResource } from './resources/data-elements.js';
import { DownloadsResource } from './resources/downloads.js';
import { TableDescriptionsResource } from './resources/table-descriptions.js';
import { DocumentsResource } from './resources/documents.js';
import { MetadataModelCatalogResource } from './resources/metadata-model-catalog.js';
import { PromptsResource } from './resources/prompts.js';
import { SessionsResource } from './resources/sessions.js';

export interface ClientOptions extends HttpClientOptions {
  /** API key for authentication */
  apiKey?: string;
  /** Bearer token for authentication */
  bearerToken?: string;
}

export class MeibelClient {
  private readonly http: HttpClient;

  public readonly agents: AgentsResource;
  public readonly artifactSchemas: ArtifactSchemasResource;
  public readonly confidenceScoring: ConfidenceScoringResource;
  public readonly datasources: DatasourcesResource;
  public readonly documents: DocumentsResource;
  public readonly metadataModelCatalog: MetadataModelCatalogResource;
  public readonly prompts: PromptsResource;
  public readonly sessions: SessionsResource;

  constructor(options: ClientOptions = {}) {
    const baseUrl = options.baseUrl ?? "https://api.meibel.ai/v2";
    const headers: Record<string, string> = { ...options.headers };

    if (options.apiKey) {
      headers["Meibel-API-Key"] = options.apiKey;
    }
    if (options.bearerToken) {
      headers["Authorization"] = `Bearer ${options.bearerToken}`;
    }

    this.http = new HttpClient({
      ...options,
      baseUrl,
      headers,
    });

    this.agents = new AgentsResource(this.http);
    this.artifactSchemas = new ArtifactSchemasResource(this.http);
    this.confidenceScoring = new ConfidenceScoringResource(this.http);
    this.datasources = new DatasourcesResource(this.http);
    this.documents = new DocumentsResource(this.http);
    this.metadataModelCatalog = new MetadataModelCatalogResource(this.http);
    this.prompts = new PromptsResource(this.http);
    this.sessions = new SessionsResource(this.http);
  }
}
