/**
 * Metadata Schema Helpers
 *
 * Converts Zod schemas into MetadataConfigRequest objects,
 * so users can define extraction schemas with native TypeScript types.
 *
 * Generated by Forge SDK Generator.
 */

import { z } from "zod";

/** Meibel metadata field type strings. */
type MeibelFieldType =
  | "string"
  | "integer"
  | "float"
  | "boolean"
  | "datetime"
  | "uuid"
  | "geo"
  | "list[string]";

/** A single metadata field definition. */
interface MetadataField {
  name: string;
  type: MeibelFieldType;
  description: string;
  index: boolean;
}

/** Shape of a MetadataConfigRequest for custom schemas. */
interface MetadataConfigCustom {
  type: "custom";
  fields: MetadataField[];
}

/**
 * Resolve a Zod type to its inner type (unwrapping optionals, defaults, etc.).
 */
function unwrapZodType(zodType: z.ZodTypeAny): z.ZodTypeAny {
  if (zodType instanceof z.ZodOptional || zodType instanceof z.ZodNullable) {
    return unwrapZodType((zodType as any)._def.innerType);
  }
  if (zodType instanceof z.ZodDefault) {
    return unwrapZodType((zodType as any)._def.innerType);
  }
  return zodType;
}

/**
 * Map a Zod type to a Meibel metadata field type string.
 */
function resolveMeibelType(
  zodType: z.ZodTypeAny,
  fieldName: string
): MeibelFieldType {
  const inner = unwrapZodType(zodType);

  if (inner instanceof z.ZodString) {
    // Check for uuid refinement via description hint
    const desc = inner.description ?? "";
    if (desc.toLowerCase().includes("uuid")) return "uuid";
    return "string";
  }
  if (inner instanceof z.ZodNumber) {
    // Distinguish integer vs float by checking for int refinements
    const checks = (inner as any)._def.checks as Array<{ kind: string }> | undefined;
    if (checks?.some((c) => c.kind === "int")) return "integer";
    return "float";
  }
  if (inner instanceof z.ZodBoolean) return "boolean";
  if (inner instanceof z.ZodDate) return "datetime";

  // z.array(z.string()) -> "list[string]"
  if (inner instanceof z.ZodArray) {
    const itemType = unwrapZodType((inner as any)._def.type);
    if (itemType instanceof z.ZodString) return "list[string]";
  }

  // z.enum for UUID pattern
  if (inner instanceof z.ZodEnum) return "string";

  throw new TypeError(
    `Cannot map Zod type for field '${fieldName}' to a Meibel metadata type. ` +
      `Supported types: z.string(), z.number(), z.number().int(), z.boolean(), ` +
      `z.date(), z.array(z.string())`
  );
}

/**
 * Convert a Zod object schema into a MetadataConfigRequest.
 *
 * @example
 * ```typescript
 * import { z } from "zod";
 * import { metadataSchemaFromZod } from "meibel/metadata";
 *
 * const InvoiceMetadata = z.object({
 *   vendor_name: z.string().describe("Name of the vendor"),
 *   total_amount: z.number().describe("Invoice total"),
 *   due_date: z.date().describe("Payment due date"),
 *   line_items: z.array(z.string()).describe("Line item descriptions"),
 * });
 *
 * const datasource = await client.datasources.create({
 *   name: "Invoices",
 *   connector: { type: "cloud_storage", ... },
 *   metadataConfig: metadataSchemaFromZod(InvoiceMetadata),
 * });
 * ```
 *
 * @param schema - A Zod object schema (z.object({...})).
 * @param options - Per-field overrides for index behavior.
 * @returns A MetadataConfigRequest-shaped object with type "custom".
 */
export function metadataSchemaFromZod(
  schema: z.ZodObject<any>,
  options?: {
    /** Fields to exclude from indexing (default: all indexed). */
    noIndex?: string[];
  }
): MetadataConfigCustom {
  const shape = schema.shape as Record<string, z.ZodTypeAny>;
  const noIndex = new Set(options?.noIndex ?? []);
  const fields: MetadataField[] = [];

  for (const [name, zodType] of Object.entries(shape)) {
    const meibelType = resolveMeibelType(zodType, name);
    const description = zodType.description ?? name.replace(/_/g, " ");

    fields.push({
      name,
      type: meibelType,
      description,
      index: !noIndex.has(name),
    });
  }

  return {
    type: "custom",
    fields,
  };
}