/**
 * Zod schemas and TypeScript types for API models.
 *
 * Generated by Forge SDK Generator.
 */

import { z } from 'zod';

/**
 * ActivityStatus
 */
export const ActivityStatusSchema = z.object({
});

/**
 * AddActivityRequest
 */
export const AddActivityRequestSchema = z.object({
  activityType: z.string(),
  inputData: z.union([z.string(), z.null()]).optional(),
  outputData: z.union([z.string(), z.null()]).optional(),
  groupId: z.union([z.string(), z.null()]).optional(),
  taskMetadata: z.union([z.string(), z.null()]).optional(),
  status: z.union([z.string(), z.null()]).optional(),
});

/**
 * AddActivityResponse
 */
export const AddActivityResponseSchema = z.object({
  id: z.string(),
});

/**
 * AddBlueprintInstanceRequest
 */
export const AddBlueprintInstanceRequestSchema = z.object({
  blueprintId: z.union([z.string(), z.null()]).optional(),
  workflowType: z.union([z.string(), z.null()]).optional(),
  taskQueue: z.union([z.string(), z.null()]).optional(),
  instanceMetadata: z.union([z.string(), z.null()]).optional(),
  parentId: z.union([z.string(), z.null()]).optional(),
});

/**
 * AddBlueprintInstanceResponse
 */
export const AddBlueprintInstanceResponseSchema = z.object({
  id: z.string(),
});

/**
 * AddBlueprintResponse
 */
export const AddBlueprintResponseSchema = z.object({
  id: z.string(),
});

/**
 * AddBlueprintTaskRequest
 */
export const AddBlueprintTaskRequestSchema = z.object({
  name: z.string(),
  type: z.union([z.string(), z.null()]).optional(),
  description: z.union([z.string(), z.null()]).optional(),
  inputSchema: z.string(),
  outputSchema: z.string(),
  configSchema: z.union([z.string(), z.null()]).optional(),
  toolSchema: z.union([z.string(), z.null()]).optional(),
});

/**
 * AddChunkingStrategyResponse
 */
export const AddChunkingStrategyResponseSchema = z.object({
  message: z.string(),
});

/**
 * AddDataElementResponse
 */
export const AddDataElementResponseSchema = z.object({
  id: z.string(),
});

/**
 * AddDatasourceResponse
 */
export const AddDatasourceResponseSchema = z.object({
  id: z.string(),
});

/**
 * AddEventResponse
 */
export const AddEventResponseSchema = z.object({
  id: z.string(),
});

/**
 * AddRagConfigResponse
 */
export const AddRagConfigResponseSchema = z.object({
  message: z.string(),
});

/**
 * AddTagColumnRequest
 */
export const AddTagColumnRequestSchema = z.object({
  description: z.union([z.string(), z.null()]).optional(),
  dtype: z.union([z.string(), z.null()]).optional(),
  isKey: z.union([z.boolean(), z.null()]).optional(),
  isIndexed: z.union([z.boolean(), z.null()]).optional(),
  engineeredFeatures: z.union([z.array(z.string()), z.null()]).optional(),
});

/**
 * AddTagColumnResponse
 */
export const AddTagColumnResponseSchema = z.object({
  message: z.string(),
});

/**
 * AddTagConfigResponse
 */
export const AddTagConfigResponseSchema = z.object({
  message: z.string(),
});

/**
 * AddTagTableRequest
 */
export const AddTagTableRequestSchema = z.object({
  description: z.union([z.string(), z.null()]).optional(),
});

/**
 * AddTagTableResponse
 */
export const AddTagTableResponseSchema = z.object({
  message: z.string(),
});

/**
 * AirbyteConfig
 */
export const AirbyteConfigSchema = z.object({
  sourceId: z.string(),
  destinationId: z.string(),
  connectionId: z.union([z.string(), z.null()]).optional(),
});

/**
 * AllowedDataElementFilterKeys
 */
export const AllowedDataElementFilterKeysSchema = z.object({
});

/**
 * A generated artifact/file from the chat agent.
 */
export const ArtifactSchema = z.object({
  artifactId: z.string(),
  filename: z.string(),
  mimeType: z.string(),
  content: z.union([z.string(), z.null()]).optional(),
  storageUrl: z.union([z.string(), z.null()]).optional(),
  sizeBytes: z.union([z.number().int(), z.null()]).optional(),
  createdAt: z.union([z.string(), z.null()]).optional(),
});

/**
 * BasicWebAuth
 */
export const BasicWebAuthSchema = z.object({
  username: z.string(),
  password: z.string(),
});

/**
 * BlueprintExecutionMode
 */
export const BlueprintExecutionModeSchema = z.object({
});

/**
 * BlueprintInstanceStatus
 */
export const BlueprintInstanceStatusSchema = z.object({
});

/**
 * An action the user can take.
 */
export const CallToActionSchema = z.object({
  label: z.string(),
  action: z.string(),
  actionData: z.union([z.string(), z.null()]).optional(),
});

/**
 * Request body for chat message endpoints.
 */
export const ChatMessageRequestSchema = z.object({
  /** The user's chat message */
  userMessage: z.string(),
  timeoutSeconds: z.union([z.number().int(), z.null()]).optional(),
  includeThinking: z.union([z.boolean(), z.null()]).optional(),
  includeToolActivity: z.union([z.boolean(), z.null()]).optional(),
});

/**
 * CodeChunking
 */
export const CodeChunkingSchema = z.object({
  chunkLines: z.union([z.number().int(), z.null()]).optional(),
  chunkLinesOverlap: z.union([z.number().int(), z.null()]).optional(),
  maxChars: z.union([z.number().int(), z.null()]).optional(),
});

/**
 * CompleteBlueprintInstanceRequest
 */
export const CompleteBlueprintInstanceRequestSchema = z.object({
  result: z.union([z.string(), z.null()]).optional(),
});

/**
 * ContentType
 */
export const ContentTypeSchema = z.object({
});

/**
 * CustomEventRequest
 */
export const CustomEventRequestSchema = z.object({
  activityId: z.union([z.string(), z.null()]).optional(),
  /** Name of the custom event being logged. */
  eventName: z.string(),
  details: z.union([z.string(), z.null()]).optional(),
  groupId: z.union([z.string(), z.null()]).optional(),
  isSignal: z.union([z.boolean(), z.null()]).optional(),
  isInternal: z.union([z.boolean(), z.null()]).optional(),
  originatingSignalId: z.union([z.string(), z.null()]).optional(),
});

/**
 * DataElementCondition
 */
export const DataElementConditionSchema = z.object({
});

/**
 * DataElementDiscoveryRecord
 */
export const DataElementDiscoveryRecordSchema = z.object({
  discoveryTime: z.string(),
  lastModifiedTime: z.string(),
  size: z.union([z.number(), z.number().int()]),
  elementHash: z.string(),
  fileId: z.union([z.string(), z.null()]).optional(),
  fileCreatedAt: z.union([z.string(), z.null()]).optional(),
  fileModifiedAt: z.union([z.string(), z.null()]).optional(),
  /** Connector-specific extra metadata */
  extra: z.union([z.string(), z.null()]).optional(),
});

/**
 * DatabaseType
 */
export const DatabaseTypeSchema = z.object({
});

/**
 * DeleteChunkingStrategyResponse
 */
export const DeleteChunkingStrategyResponseSchema = z.object({
  message: z.string(),
});

/**
 * DeleteContentResponse
 */
export const DeleteContentResponseSchema = z.object({
  success: z.boolean(),
  deletedPaths: z.array(z.string()),
});

/**
 * DeleteDataElementResponse
 */
export const DeleteDataElementResponseSchema = z.object({
  id: z.string(),
});

/**
 * DeleteDatasourceResponse
 */
export const DeleteDatasourceResponseSchema = z.object({
  id: z.string(),
});

/**
 * DeleteTagTableResponse
 */
export const DeleteTagTableResponseSchema = z.object({
  message: z.string(),
});

/**
 * DslDefinition
 */
export const DslDefinitionSchema = z.object({
});

/**
 * EmbeddingModel
 */
export const EmbeddingModelSchema = z.object({
  name: z.string(),
  endpoint: z.string(),
  dimensions: z.number().int(),
});

/**
 * EventType
 */
export const EventTypeSchema = z.object({
});

/**
 * ExecuteBlueprintRequest
 */
export const ExecuteBlueprintRequestSchema = z.object({
  initInput: z.union([z.string(), z.null()]).optional(),
  enableStreaming: z.union([z.boolean(), z.null()]).optional(),
});

/**
 * ExtractorModel
 */
export const ExtractorModelSchema = z.object({
  name: z.string(),
  endpoint: z.string(),
});

/**
 * FailBlueprintInstanceRequest
 */
export const FailBlueprintInstanceRequestSchema = z.object({
  /** Error message for failure */
  error: z.union([z.string(), z.null()]).optional(),
  errorDetails: z.union([z.string(), z.null()]).optional(),
});

/**
 * GetAllDatasourceIdsResponse
 */
export const GetAllDatasourceIdsResponseSchema = z.object({
  datasourceIds: z.array(z.string()),
});

/**
 * HTMLChunking
 */
export const HtmlChunkingSchema = z.object({
  includeMetadata: z.boolean(),
  includePrevNextRel: z.boolean(),
  tags: z.union([z.array(z.string()), z.null()]).optional(),
});

/**
 * JSONNodeChunking
 */
export const JsonNodeChunkingSchema = z.object({
  includeMetadata: z.boolean(),
  includePrevNextRel: z.boolean(),
});

/**
 * MarkdownNodeChunking
 */
export const MarkdownNodeChunkingSchema = z.object({
  includeMetadata: z.boolean(),
  includePrevNextRel: z.boolean(),
  headerPathSeparator: z.string(),
});

/**
 * MetadataOptions
 */
export const MetadataOptionsSchema = z.object({
  createTitle: z.union([z.boolean(), z.null()]).optional(),
  extractQuestionsAnswers: z.union([z.boolean(), z.null()]).optional(),
  extractSummary: z.union([z.boolean(), z.null()]).optional(),
  hasConsumerContent: z.union([z.boolean(), z.null()]).optional(),
  getBibliographicalInformation: z.union([z.boolean(), z.null()]).optional(),
});

/**
 * ObjectStorageFilters
 */
export const ObjectStorageFiltersSchema = z.object({
  includedPrefixes: z.union([z.array(z.string()), z.null()]).optional(),
  includedFileTypes: z.union([z.array(z.string()), z.null()]).optional(),
  recursivePrefixes: z.union([z.boolean(), z.null()]).optional(),
  modifiedDateStart: z.union([z.string(), z.null()]).optional(),
  modifiedDateEnd: z.union([z.string(), z.null()]).optional(),
  minFileSize: z.union([z.number().int(), z.null()]).optional(),
  maxFileSize: z.union([z.number().int(), z.null()]).optional(),
});

/**
 * Platform
 */
export const PlatformSchema = z.object({
});

/**
 * S3Config
 */
export const S3ConfigSchema = z.object({
  roleArn: z.string(),
  region: z.string(),
});

/**
 * SemanticChunking
 */
export const SemanticChunkingSchema = z.object({
  bufferSize: z.union([z.number().int(), z.null()]).optional(),
  includeMetadata: z.boolean(),
  includePrevNextRel: z.boolean(),
  breakpointPercentileThreshold: z.union([z.number().int(), z.null()]).optional(),
});

/**
 * SentenceChunking
 */
export const SentenceChunkingSchema = z.object({
  chunkSize: z.union([z.number().int(), z.null()]).optional(),
  chunkOverlap: z.union([z.number().int(), z.null()]).optional(),
  separator: z.union([z.string(), z.null()]).optional(),
  paragraphSeparator: z.union([z.string(), z.null()]).optional(),
  secondaryChunkingRegex: z.union([z.string(), z.null()]).optional(),
});

/**
 * A source/citation in the response.
 */
export const SourceSchema = z.object({
  title: z.string(),
  url: z.union([z.string(), z.null()]).optional(),
  snippet: z.union([z.string(), z.null()]).optional(),
  dataElementId: z.union([z.string(), z.null()]).optional(),
  relevanceScore: z.union([z.number(), z.number().int(), z.null()]).optional(),
});

/**
 * SparseEmbeddingModel
 */
export const SparseEmbeddingModelSchema = z.object({
  name: z.string(),
  endpoint: z.string(),
});

/**
 * StartBlueprintInstanceRequest
 */
export const StartBlueprintInstanceRequestSchema = z.object({
  workflowArgs: z.union([z.array(z.string()), z.null()]).optional(),
  workflowKwargs: z.union([z.string(), z.null()]).optional(),
  /** Enable streaming responses to Redis for chat workflows. When True, chat responses are streamed to Redis streams that can be consumed via the /chat/stream endpoint. */
  enableStreaming: z.union([z.boolean(), z.null()]).optional(),
});

/**
 * TagColumnInfo
 */
export const TagColumnInfoSchema = z.object({
  datasourceId: z.string(),
  tableName: z.string(),
  name: z.string(),
  description: z.union([z.string(), z.null()]),
  dtype: z.union([z.string(), z.null()]),
  isKey: z.union([z.boolean(), z.null()]),
  isIndexed: z.union([z.boolean(), z.null()]),
  engineeredFeatures: z.union([z.array(z.string()), z.null()]),
});

/**
 * TagTableInfo
 */
export const TagTableInfoSchema = z.object({
  datasourceId: z.string(),
  name: z.string(),
  description: z.union([z.string(), z.null()]),
});

/**
 * TokenTextChunking
 */
export const TokenTextChunkingSchema = z.object({
  chunkSize: z.union([z.number().int(), z.null()]).optional(),
  chunkOverlap: z.union([z.number().int(), z.null()]).optional(),
  separator: z.union([z.string(), z.null()]).optional(),
  backupSeparators: z.union([z.array(z.string()), z.null()]).optional(),
  keepWhitespaces: z.union([z.boolean(), z.null()]).optional(),
});

/**
 * Record of a tool call and its result.
 */
export const ToolActivitySchema = z.object({
  toolId: z.string(),
  toolName: z.string(),
  arguments: z.string(),
  result: z.union([z.string(), z.null()]).optional(),
  timestamp: z.string(),
});

/**
 * UpdateBlueprintTaskRequest
 */
export const UpdateBlueprintTaskRequestSchema = z.object({
  name: z.union([z.string(), z.null()]).optional(),
  description: z.union([z.string(), z.null()]).optional(),
  inputSchema: z.union([z.string(), z.null()]).optional(),
  outputSchema: z.union([z.string(), z.null()]).optional(),
  configSchema: z.union([z.string(), z.null()]).optional(),
  toolSchema: z.union([z.string(), z.null()]).optional(),
});

/**
 * UpdateChunkingStrategyResponse
 */
export const UpdateChunkingStrategyResponseSchema = z.object({
  message: z.string(),
});

/**
 * UpdateDataElementResponse
 */
export const UpdateDataElementResponseSchema = z.object({
  id: z.string(),
});

/**
 * UpdateDatasourceResponse
 */
export const UpdateDatasourceResponseSchema = z.object({
  id: z.string(),
});

/**
 * UpdateRagConfigResponse
 */
export const UpdateRagConfigResponseSchema = z.object({
  message: z.string(),
});

/**
 * UpdateTagColumnRequest
 */
export const UpdateTagColumnRequestSchema = z.object({
  description: z.union([z.string(), z.null()]).optional(),
  dtype: z.union([z.string(), z.null()]).optional(),
  isKey: z.union([z.boolean(), z.null()]).optional(),
  isIndexed: z.union([z.boolean(), z.null()]).optional(),
  engineeredFeatures: z.union([z.array(z.string()), z.null()]).optional(),
});

/**
 * UpdateTagColumnResponse
 */
export const UpdateTagColumnResponseSchema = z.object({
  message: z.string(),
});

/**
 * UpdateTagConfigResponse
 */
export const UpdateTagConfigResponseSchema = z.object({
  message: z.string(),
});

/**
 * UpdateTagTableRequest
 */
export const UpdateTagTableRequestSchema = z.object({
  description: z.union([z.string(), z.null()]).optional(),
});

/**
 * UpdateTagTableResponse
 */
export const UpdateTagTableResponseSchema = z.object({
  message: z.string(),
});

/**
 * UploadContentResponse
 */
export const UploadContentResponseSchema = z.object({
  success: z.boolean(),
  message: z.string(),
  uploadId: z.string(),
  sseUrl: z.string(),
  estimatedFiles: z.number().int(),
  estimatedSize: z.number().int(),
});

export const ValidationErrorSchema = z.object({
  loc: z.array(z.union([z.string(), z.number().int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * WebDomain
 */
export const WebDomainSchema = z.object({
  domain: z.string(),
  limitPattern: z.string(),
  excludePattern: z.string(),
  ingestible: z.boolean(),
  expandable: z.boolean(),
});

/**
 * A server-sent event indicating that the server is still processing the request
 */
export const HeartbeatEventSchema = z.object({
  event: z.string(),
});

/**
 * A server-sent event containing chat completion content
 */
export const ChatEventSchema = z.object({
  id: z.string(),
  event: z.string(),
  data: z.string(),
});

/**
 * Generic Server-Sent Event
 */
export const SseEventSchema = z.object({
  /** Event type (e.g., connected, progress, stream_complete, error, keepalive) */
  event: z.string(),
  /** Event data payload */
  data: z.string().optional(),
});

/**
 * Activity
 */
export const ActivitySchema = z.object({
  id: z.union([z.string(), z.null()]).optional(),
  blueprintInstanceId: z.string(),
  activityType: z.string(),
  status: z.union([ActivityStatusSchema, z.null()]).optional(),
  startTime: z.union([z.coerce.date(), z.null()]).optional(),
  endTime: z.union([z.coerce.date(), z.null()]).optional(),
  inputData: z.union([z.string(), z.null()]).optional(),
  outputData: z.union([z.string(), z.null()]).optional(),
  error: z.union([z.string(), z.null()]).optional(),
  groupId: z.union([z.string(), z.null()]).optional(),
  taskMetadata: z.union([z.string(), z.null()]).optional(),
});

/**
 * DatasourceConnectorConfig
 */
export const DatasourceConnectorConfigSchema = z.object({
  connectorId: z.string(),
  airbyteConfig: z.union([AirbyteConfigSchema, z.null()]).optional(),
  sourceConfig: z.union([z.string(), z.null()]).optional(),
});

/**
 * ContentItem
 */
export const ContentItemSchema = z.object({
  name: z.string(),
  path: z.string(),
  type: ContentTypeSchema,
  size: z.union([z.number().int(), z.null()]).optional(),
  mediaType: z.union([z.string(), z.null()]).optional(),
  lastModified: z.union([z.string(), z.null()]).optional(),
  etag: z.union([z.string(), z.null()]).optional(),
});

/**
 * GetContentResponse
 */
export const GetContentResponseSchema = z.object({
  name: z.string(),
  path: z.string(),
  type: ContentTypeSchema,
  size: z.union([z.number().int(), z.null()]).optional(),
  mediaType: z.union([z.string(), z.null()]).optional(),
  lastModified: z.union([z.string(), z.null()]).optional(),
  etag: z.union([z.string(), z.null()]).optional(),
  metadata: z.union([z.string(), z.null()]).optional(),
});

/**
 * DataElementFilter
 */
export const DataElementFilterSchema = z.object({
  key: AllowedDataElementFilterKeysSchema,
  condition: z.union([DataElementConditionSchema, z.null()]).optional(),
  value: z.union([z.string(), z.null()]),
});

/**
 * AddDataElementRequest
 */
export const AddDataElementRequestSchema = z.object({
  description: z.union([z.string(), z.null()]),
  name: z.string(),
  path: z.string(),
  mediaType: z.string(),
  discoveryRecord: z.union([DataElementDiscoveryRecordSchema, z.null()]),
  parentDataElementId: z.union([z.string(), z.null()]).optional(),
});

/**
 * DataElement
 */
export const DataElementSchema = z.object({
  id: z.union([z.string(), z.null()]),
  datasourceId: z.string(),
  name: z.string(),
  path: z.string(),
  mediaType: z.string(),
  discoveryRecord: z.union([DataElementDiscoveryRecordSchema, z.null()]),
  description: z.union([z.string(), z.null()]),
  parentDataElementId: z.union([z.string(), z.null()]).optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * UpdateDataElementRequest
 */
export const UpdateDataElementRequestSchema = z.object({
  description: z.union([z.string(), z.null()]).optional(),
  name: z.union([z.string(), z.null()]).optional(),
  path: z.union([z.string(), z.null()]).optional(),
  mediaType: z.union([z.string(), z.null()]).optional(),
  discoveryRecord: z.union([DataElementDiscoveryRecordSchema, z.null()]).optional(),
  parentDataElementId: z.union([z.string(), z.null()]).optional(),
});

/**
 * ClickhouseConfig
 */
export const ClickhouseConfigSchema = z.object({
  databaseType: z.union([DatabaseTypeSchema, z.null()]).optional(),
  databaseName: z.string(),
});

/**
 * DuckDBConfig
 */
export const DuckDbConfigSchema = z.object({
  databaseType: z.union([DatabaseTypeSchema, z.null()]).optional(),
  databaseFilepath: z.union([z.string(), z.null()]).optional(),
  databaseName: z.union([z.string(), z.null()]).optional(),
  databaseSchema: z.union([z.string(), z.null()]).optional(),
});

/**
 * PostgreSQLConfig
 */
export const PostgreSqlConfigSchema = z.object({
  databaseType: z.union([DatabaseTypeSchema, z.null()]).optional(),
  databaseName: z.string(),
});

/**
 * AddBlueprintRequest
 */
export const AddBlueprintRequestSchema = z.object({
  name: z.string(),
  executionMode: z.union([z.string(), z.null()]).optional(),
  version: z.union([z.string(), z.null()]).optional(),
  description: z.union([z.string(), z.null()]).optional(),
  dslDefinition: DslDefinitionSchema,
  yamlSpecContent: z.union([z.string(), z.null()]).optional(),
  jsonSpecContent: z.union([z.string(), z.null()]).optional(),
  workflowType: z.union([z.string(), z.null()]).optional(),
  workflowTaskQueue: z.union([z.string(), z.null()]).optional(),
  initInput: z.union([z.string(), z.null()]).optional(),
});

/**
 * Blueprint
 */
export const BlueprintSchema = z.object({
  id: z.union([z.string(), z.null()]).optional(),
  name: z.string(),
  executionMode: z.union([BlueprintExecutionModeSchema, z.null()]).optional(),
  chatSignal: z.union([z.string(), z.null()]).optional(),
  version: z.union([z.string(), z.null()]).optional(),
  description: z.union([z.string(), z.null()]).optional(),
  dslDefinition: DslDefinitionSchema,
  yamlSpecContent: z.union([z.string(), z.null()]).optional(),
  jsonSpecContent: z.union([z.string(), z.null()]).optional(),
  createdBy: z.union([z.string(), z.null()]).optional(),
  updatedBy: z.union([z.string(), z.null()]).optional(),
  createdAt: z.union([z.coerce.date(), z.null()]).optional(),
  updatedAt: z.union([z.coerce.date(), z.null()]).optional(),
  customerId: z.string(),
  projectId: z.string(),
  workflowType: z.union([z.string(), z.null()]).optional(),
  workflowTaskQueue: z.union([z.string(), z.null()]).optional(),
  initInput: z.union([z.string(), z.null()]).optional(),
});

/**
 * UpdateBlueprintRequest
 */
export const UpdateBlueprintRequestSchema = z.object({
  name: z.union([z.string(), z.null()]).optional(),
  executionMode: z.union([z.string(), z.null()]).optional(),
  version: z.union([z.string(), z.null()]).optional(),
  description: z.union([z.string(), z.null()]).optional(),
  dslDefinition: z.union([DslDefinitionSchema, z.null()]).optional(),
  yamlSpecContent: z.union([z.string(), z.null()]).optional(),
  jsonSpecContent: z.union([z.string(), z.null()]).optional(),
  initInput: z.union([z.string(), z.null()]).optional(),
});

/**
 * Event
 */
export const EventSchema = z.object({
  id: z.union([z.string(), z.null()]).optional(),
  activityId: z.union([z.string(), z.null()]).optional(),
  blueprintInstanceId: z.string(),
  eventType: z.union([EventTypeSchema, z.null()]).optional(),
  timestamp: z.union([z.coerce.date(), z.null()]).optional(),
  details: z.union([z.string(), z.null()]).optional(),
  groupId: z.union([z.string(), z.null()]).optional(),
  isSignal: z.union([z.boolean(), z.null()]).optional(),
  isInternal: z.union([z.boolean(), z.null()]).optional(),
  originatingSignalId: z.union([z.string(), z.null()]).optional(),
});

/**
 * ObjectStorageConfig
 */
export const ObjectStorageConfigSchema = z.object({
  bucket: z.string(),
  prefix: z.union([z.string(), z.null()]),
  filters: z.union([ObjectStorageFiltersSchema, z.null()]).optional(),
  gcsConfig: z.union([z.string(), z.null()]).optional(),
  s3Config: z.union([S3ConfigSchema, z.null()]).optional(),
});

/**
 * The structured chat response.
 */
export const ChatResponseSchema = z.object({
  message: z.union([z.string(), z.null()]).optional(),
  sources: z.union([z.array(SourceSchema), z.null()]).optional(),
  followUpQuestions: z.union([z.array(z.string()), z.null()]).optional(),
  callToActions: z.union([z.array(CallToActionSchema), z.null()]).optional(),
  artifacts: z.union([z.array(ArtifactSchema), z.null()]).optional(),
});

/**
 * AddRagConfigRequest
 */
export const AddRagConfigRequestSchema = z.object({
  description: z.union([z.string(), z.null()]).optional(),
  collectionId: z.string(),
  extractorModel: z.union([ExtractorModelSchema, z.null()]).optional(),
  embeddingModel: z.union([EmbeddingModelSchema, z.null()]).optional(),
  sparseEmbeddingModel: z.union([SparseEmbeddingModelSchema, z.null()]).optional(),
  collectMetadata: z.union([z.boolean(), z.null()]).optional(),
  metadataOptions: z.union([MetadataOptionsSchema, z.null()]).optional(),
});

/**
 * RagConfig
 */
export const RagConfigSchema = z.object({
  datasourceId: z.string(),
  description: z.string(),
  collectionId: z.string(),
  extractorModel: z.union([ExtractorModelSchema, z.null()]).optional(),
  embeddingModel: z.union([EmbeddingModelSchema, z.null()]).optional(),
  sparseEmbeddingModel: z.union([SparseEmbeddingModelSchema, z.null()]).optional(),
  collectMetadata: z.union([z.boolean(), z.null()]).optional(),
  metadataOptions: z.union([MetadataOptionsSchema, z.null()]).optional(),
  createdBy: z.union([z.string(), z.null()]).optional(),
  updatedBy: z.union([z.string(), z.null()]).optional(),
});

/**
 * UpdateRagConfigRequest
 */
export const UpdateRagConfigRequestSchema = z.object({
  description: z.union([z.string(), z.null()]).optional(),
  collectionId: z.union([z.string(), z.null()]).optional(),
  extractorModel: z.union([ExtractorModelSchema, z.null()]).optional(),
  embeddingModel: z.union([EmbeddingModelSchema, z.null()]).optional(),
  sparseEmbeddingModel: z.union([SparseEmbeddingModelSchema, z.null()]).optional(),
  collectMetadata: z.union([z.boolean(), z.null()]).optional(),
  metadataOptions: z.union([MetadataOptionsSchema, z.null()]).optional(),
});

/**
 * AddChunkingStrategyRequest
 */
export const AddChunkingStrategyRequestSchema = z.object({
  codeSplitter: z.union([CodeChunkingSchema, z.null()]).optional(),
  htmlNodeParser: z.union([HtmlChunkingSchema, z.null()]).optional(),
  jsonNodeParser: z.union([JsonNodeChunkingSchema, z.null()]).optional(),
  markdownNodeParser: z.union([MarkdownNodeChunkingSchema, z.null()]).optional(),
  semanticSplitterNodeParser: z.union([SemanticChunkingSchema, z.null()]).optional(),
  sentenceSplitter: z.union([SentenceChunkingSchema, z.null()]).optional(),
  tokenTextSplitter: z.union([TokenTextChunkingSchema, z.null()]).optional(),
});

/**
 * RagChunkingStrategy
 */
export const RagChunkingStrategySchema = z.object({
  datasourceId: z.string(),
  codeSplitter: z.union([CodeChunkingSchema, z.null()]).optional(),
  htmlNodeParser: z.union([HtmlChunkingSchema, z.null()]).optional(),
  jsonNodeParser: z.union([JsonNodeChunkingSchema, z.null()]).optional(),
  markdownNodeParser: z.union([MarkdownNodeChunkingSchema, z.null()]).optional(),
  semanticSplitterNodeParser: z.union([SemanticChunkingSchema, z.null()]).optional(),
  sentenceSplitter: z.union([SentenceChunkingSchema, z.null()]).optional(),
  tokenTextSplitter: z.union([TokenTextChunkingSchema, z.null()]).optional(),
});

/**
 * UpdateChunkingStrategyRequest
 */
export const UpdateChunkingStrategyRequestSchema = z.object({
  codeSplitter: z.union([CodeChunkingSchema, z.null()]).optional(),
  htmlNodeParser: z.union([HtmlChunkingSchema, z.null()]).optional(),
  jsonNodeParser: z.union([JsonNodeChunkingSchema, z.null()]).optional(),
  markdownNodeParser: z.union([MarkdownNodeChunkingSchema, z.null()]).optional(),
  semanticSplitterNodeParser: z.union([SemanticChunkingSchema, z.null()]).optional(),
  sentenceSplitter: z.union([SentenceChunkingSchema, z.null()]).optional(),
  tokenTextSplitter: z.union([TokenTextChunkingSchema, z.null()]).optional(),
});

export const HttpValidationErrorSchema = z.object({
  detail: z.array(ValidationErrorSchema).optional(),
});

/**
 * DatasourceWebConfig
 */
export const DatasourceWebConfigSchema = z.object({
  baseUrl: z.string(),
  javascriptRender: z.boolean(),
  waitForSelector: z.union([z.string(), z.null()]),
  domains: z.union([z.array(WebDomainSchema), z.null()]),
  authentication: z.union([BasicWebAuthSchema, z.null()]),
});

/**
 * GetActivitiesResponse
 */
export const GetActivitiesResponseSchema = z.object({
  data: z.array(ActivitySchema),
});

/**
 * ListContentResponse
 */
export const ListContentResponseSchema = z.object({
  items: z.array(ContentItemSchema),
  continuationToken: z.union([z.string(), z.null()]).optional(),
});

/**
 * DataElementFilterRequest
 */
export const DataElementFilterRequestSchema = z.object({
  filters: z.union([z.array(DataElementFilterSchema), z.null()]).optional(),
});

/**
 * DatabaseConfig
 */
export const DatabaseConfigInputSchema = z.object({
  anyofSchema_1Validator: z.union([DuckDbConfigSchema, z.null()]).optional(),
  anyofSchema_2Validator: z.union([ClickhouseConfigSchema, z.null()]).optional(),
  anyofSchema_3Validator: z.union([PostgreSqlConfigSchema, z.null()]).optional(),
  actualInstance: z.string().optional(),
  anyOfSchemas: z.array(z.string()).optional(),
});

/**
 * DatabaseConfig
 */
export const DatabaseConfigOutputSchema = z.object({
  anyofSchema_1Validator: z.union([DuckDbConfigSchema, z.null()]).optional(),
  anyofSchema_2Validator: z.union([ClickhouseConfigSchema, z.null()]).optional(),
  anyofSchema_3Validator: z.union([PostgreSqlConfigSchema, z.null()]).optional(),
  actualInstance: z.string().optional(),
  anyOfSchemas: z.array(z.string()).optional(),
});

/**
 * GetBlueprintsResponse
 */
export const GetBlueprintsResponseSchema = z.object({
  data: z.array(BlueprintSchema),
});

/**
 * BlueprintInstance
 */
export const BlueprintInstanceSchema = z.object({
  id: z.union([z.string(), z.null()]).optional(),
  blueprintId: z.union([z.string(), z.null()]).optional(),
  workflowType: z.union([z.string(), z.null()]).optional(),
  taskQueue: z.union([z.string(), z.null()]).optional(),
  workflowRunId: z.union([z.string(), z.null()]).optional(),
  status: z.union([BlueprintInstanceStatusSchema, z.null()]).optional(),
  startTime: z.union([z.coerce.date(), z.null()]).optional(),
  endTime: z.union([z.coerce.date(), z.null()]).optional(),
  instanceMetadata: z.union([z.string(), z.null()]).optional(),
  parentId: z.union([z.string(), z.null()]).optional(),
  children: z.union([z.array(BlueprintInstanceSchema), z.null()]).optional(),
  activities: z.union([z.array(ActivitySchema), z.null()]).optional(),
  events: z.union([z.array(EventSchema), z.null()]).optional(),
});

/**
 * GetEventsResponse
 */
export const GetEventsResponseSchema = z.object({
  data: z.array(EventSchema),
});

/**
 * Response from the non-streaming chat endpoint.
 */
export const ChatMessageResponseSchema = z.object({
  /** Unique ID for this message exchange */
  signalId: z.string(),
  /** The structured response */
  response: ChatResponseSchema,
  /** The assistant response in text-format */
  assistantResponse: z.string(),
  toolActivity: z.union([z.array(ToolActivitySchema), z.null()]).optional(),
  thinking: z.union([z.string(), z.null()]).optional(),
  tokenUsage: z.union([z.record(z.string(), z.number().int()), z.null()]).optional(),
});

/**
 * AddDatasourceRequest
 */
export const AddDatasourceRequestSchema = z.object({
  customerId: z.string(),
  projectId: z.string(),
  name: z.string(),
  description: z.string(),
  recurrence: z.string(),
  objectStorageConfig: z.union([ObjectStorageConfigSchema, z.null()]).optional(),
  webConfig: z.union([DatasourceWebConfigSchema, z.null()]).optional(),
  connectorConfig: z.union([DatasourceConnectorConfigSchema, z.null()]).optional(),
});

/**
 * Datasource
 */
export const DatasourceSchema = z.object({
  id: z.union([z.string(), z.null()]),
  customerId: z.string(),
  projectId: z.string(),
  name: z.string(),
  description: z.string(),
  recurrence: z.union([z.string(), z.null()]),
  createdBy: z.string(),
  createdAt: z.string(),
  updatedBy: z.string(),
  updatedAt: z.string(),
  objectStorageConfig: z.union([ObjectStorageConfigSchema, z.null()]),
  webConfig: z.union([DatasourceWebConfigSchema, z.null()]),
  connectorConfig: z.union([DatasourceConnectorConfigSchema, z.null()]),
});

/**
 * UpdateDatasourceRequest
 */
export const UpdateDatasourceRequestSchema = z.object({
  name: z.union([z.string(), z.null()]).optional(),
  description: z.union([z.string(), z.null()]).optional(),
  recurrence: z.union([z.string(), z.null()]).optional(),
  objectStorageConfig: z.union([ObjectStorageConfigSchema, z.null()]).optional(),
  webConfig: z.union([DatasourceWebConfigSchema, z.null()]).optional(),
  connectorConfig: z.union([DatasourceConnectorConfigSchema, z.null()]).optional(),
});

/**
 * AddTagConfigRequest
 */
export const AddTagConfigRequestSchema = z.object({
  description: z.union([z.string(), z.null()]).optional(),
  logicalGroupRegex: z.union([z.string(), z.null()]).optional(),
  workingBucket: z.string(),
  workingPlatform: z.union([z.string(), z.null()]).optional(),
  dbPath: z.union([z.string(), z.null()]).optional(),
  databaseConfig: z.union([DatabaseConfigInputSchema, z.null()]).optional(),
});

/**
 * UpdateTagConfigRequest
 */
export const UpdateTagConfigRequestSchema = z.object({
  description: z.union([z.string(), z.null()]).optional(),
  logicalGroupRegex: z.union([z.string(), z.null()]).optional(),
  workingBucket: z.union([z.string(), z.null()]).optional(),
  workingPlatform: z.union([z.string(), z.null()]).optional(),
  dbPath: z.union([z.string(), z.null()]).optional(),
  databaseConfig: z.union([DatabaseConfigInputSchema, z.null()]).optional(),
});

/**
 * TagConfig
 */
export const TagConfigSchema = z.object({
  datasourceId: z.string(),
  description: z.union([z.string(), z.null()]),
  logicalGroupRegex: z.union([z.string(), z.null()]),
  workingBucket: z.string(),
  workingPlatform: z.union([PlatformSchema, z.null()]).optional(),
  dbPath: z.union([z.string(), z.null()]),
  databaseConfig: z.union([DatabaseConfigOutputSchema, z.null()]).optional(),
  createdBy: z.union([z.string(), z.null()]).optional(),
  updatedBy: z.union([z.string(), z.null()]).optional(),
});

/**
 * GetBlueprintInstancesResponse
 */
export const GetBlueprintInstancesResponseSchema = z.object({
  data: z.array(BlueprintInstanceSchema),
});

// Type exports
export type ActivityStatus = z.infer<typeof ActivityStatusSchema>;
export type AddActivityRequest = z.infer<typeof AddActivityRequestSchema>;
export type AddActivityResponse = z.infer<typeof AddActivityResponseSchema>;
export type AddBlueprintInstanceRequest = z.infer<typeof AddBlueprintInstanceRequestSchema>;
export type AddBlueprintInstanceResponse = z.infer<typeof AddBlueprintInstanceResponseSchema>;
export type AddBlueprintResponse = z.infer<typeof AddBlueprintResponseSchema>;
export type AddBlueprintTaskRequest = z.infer<typeof AddBlueprintTaskRequestSchema>;
export type AddChunkingStrategyResponse = z.infer<typeof AddChunkingStrategyResponseSchema>;
export type AddDataElementResponse = z.infer<typeof AddDataElementResponseSchema>;
export type AddDatasourceResponse = z.infer<typeof AddDatasourceResponseSchema>;
export type AddEventResponse = z.infer<typeof AddEventResponseSchema>;
export type AddRagConfigResponse = z.infer<typeof AddRagConfigResponseSchema>;
export type AddTagColumnRequest = z.infer<typeof AddTagColumnRequestSchema>;
export type AddTagColumnResponse = z.infer<typeof AddTagColumnResponseSchema>;
export type AddTagConfigResponse = z.infer<typeof AddTagConfigResponseSchema>;
export type AddTagTableRequest = z.infer<typeof AddTagTableRequestSchema>;
export type AddTagTableResponse = z.infer<typeof AddTagTableResponseSchema>;
export type AirbyteConfig = z.infer<typeof AirbyteConfigSchema>;
export type AllowedDataElementFilterKeys = z.infer<typeof AllowedDataElementFilterKeysSchema>;
export type Artifact = z.infer<typeof ArtifactSchema>;
export type BasicWebAuth = z.infer<typeof BasicWebAuthSchema>;
export type BlueprintExecutionMode = z.infer<typeof BlueprintExecutionModeSchema>;
export type BlueprintInstanceStatus = z.infer<typeof BlueprintInstanceStatusSchema>;
export type CallToAction = z.infer<typeof CallToActionSchema>;
export type ChatMessageRequest = z.infer<typeof ChatMessageRequestSchema>;
export type CodeChunking = z.infer<typeof CodeChunkingSchema>;
export type CompleteBlueprintInstanceRequest = z.infer<typeof CompleteBlueprintInstanceRequestSchema>;
export type ContentType = z.infer<typeof ContentTypeSchema>;
export type CustomEventRequest = z.infer<typeof CustomEventRequestSchema>;
export type DataElementCondition = z.infer<typeof DataElementConditionSchema>;
export type DataElementDiscoveryRecord = z.infer<typeof DataElementDiscoveryRecordSchema>;
export type DatabaseType = z.infer<typeof DatabaseTypeSchema>;
export type DeleteChunkingStrategyResponse = z.infer<typeof DeleteChunkingStrategyResponseSchema>;
export type DeleteContentResponse = z.infer<typeof DeleteContentResponseSchema>;
export type DeleteDataElementResponse = z.infer<typeof DeleteDataElementResponseSchema>;
export type DeleteDatasourceResponse = z.infer<typeof DeleteDatasourceResponseSchema>;
export type DeleteTagTableResponse = z.infer<typeof DeleteTagTableResponseSchema>;
export type DslDefinition = z.infer<typeof DslDefinitionSchema>;
export type EmbeddingModel = z.infer<typeof EmbeddingModelSchema>;
export type EventType = z.infer<typeof EventTypeSchema>;
export type ExecuteBlueprintRequest = z.infer<typeof ExecuteBlueprintRequestSchema>;
export type ExtractorModel = z.infer<typeof ExtractorModelSchema>;
export type FailBlueprintInstanceRequest = z.infer<typeof FailBlueprintInstanceRequestSchema>;
export type GetAllDatasourceIdsResponse = z.infer<typeof GetAllDatasourceIdsResponseSchema>;
export type HtmlChunking = z.infer<typeof HtmlChunkingSchema>;
export type JsonNodeChunking = z.infer<typeof JsonNodeChunkingSchema>;
export type MarkdownNodeChunking = z.infer<typeof MarkdownNodeChunkingSchema>;
export type MetadataOptions = z.infer<typeof MetadataOptionsSchema>;
export type ObjectStorageFilters = z.infer<typeof ObjectStorageFiltersSchema>;
export type Platform = z.infer<typeof PlatformSchema>;
export type S3Config = z.infer<typeof S3ConfigSchema>;
export type SemanticChunking = z.infer<typeof SemanticChunkingSchema>;
export type SentenceChunking = z.infer<typeof SentenceChunkingSchema>;
export type Source = z.infer<typeof SourceSchema>;
export type SparseEmbeddingModel = z.infer<typeof SparseEmbeddingModelSchema>;
export type StartBlueprintInstanceRequest = z.infer<typeof StartBlueprintInstanceRequestSchema>;
export type TagColumnInfo = z.infer<typeof TagColumnInfoSchema>;
export type TagTableInfo = z.infer<typeof TagTableInfoSchema>;
export type TokenTextChunking = z.infer<typeof TokenTextChunkingSchema>;
export type ToolActivity = z.infer<typeof ToolActivitySchema>;
export type UpdateBlueprintTaskRequest = z.infer<typeof UpdateBlueprintTaskRequestSchema>;
export type UpdateChunkingStrategyResponse = z.infer<typeof UpdateChunkingStrategyResponseSchema>;
export type UpdateDataElementResponse = z.infer<typeof UpdateDataElementResponseSchema>;
export type UpdateDatasourceResponse = z.infer<typeof UpdateDatasourceResponseSchema>;
export type UpdateRagConfigResponse = z.infer<typeof UpdateRagConfigResponseSchema>;
export type UpdateTagColumnRequest = z.infer<typeof UpdateTagColumnRequestSchema>;
export type UpdateTagColumnResponse = z.infer<typeof UpdateTagColumnResponseSchema>;
export type UpdateTagConfigResponse = z.infer<typeof UpdateTagConfigResponseSchema>;
export type UpdateTagTableRequest = z.infer<typeof UpdateTagTableRequestSchema>;
export type UpdateTagTableResponse = z.infer<typeof UpdateTagTableResponseSchema>;
export type UploadContentResponse = z.infer<typeof UploadContentResponseSchema>;
export type ValidationErrorDetail = z.infer<typeof ValidationErrorSchema>;
export type WebDomain = z.infer<typeof WebDomainSchema>;
export type HeartbeatEvent = z.infer<typeof HeartbeatEventSchema>;
export type ChatEvent = z.infer<typeof ChatEventSchema>;
export type SseEvent = z.infer<typeof SseEventSchema>;
export type Activity = z.infer<typeof ActivitySchema>;
export type DatasourceConnectorConfig = z.infer<typeof DatasourceConnectorConfigSchema>;
export type ContentItem = z.infer<typeof ContentItemSchema>;
export type GetContentResponse = z.infer<typeof GetContentResponseSchema>;
export type DataElementFilter = z.infer<typeof DataElementFilterSchema>;
export type AddDataElementRequest = z.infer<typeof AddDataElementRequestSchema>;
export type DataElement = z.infer<typeof DataElementSchema>;
export type UpdateDataElementRequest = z.infer<typeof UpdateDataElementRequestSchema>;
export type ClickhouseConfig = z.infer<typeof ClickhouseConfigSchema>;
export type DuckDbConfig = z.infer<typeof DuckDbConfigSchema>;
export type PostgreSqlConfig = z.infer<typeof PostgreSqlConfigSchema>;
export type AddBlueprintRequest = z.infer<typeof AddBlueprintRequestSchema>;
export type Blueprint = z.infer<typeof BlueprintSchema>;
export type UpdateBlueprintRequest = z.infer<typeof UpdateBlueprintRequestSchema>;
export type Event = z.infer<typeof EventSchema>;
export type ObjectStorageConfig = z.infer<typeof ObjectStorageConfigSchema>;
export type ChatResponse = z.infer<typeof ChatResponseSchema>;
export type AddRagConfigRequest = z.infer<typeof AddRagConfigRequestSchema>;
export type RagConfig = z.infer<typeof RagConfigSchema>;
export type UpdateRagConfigRequest = z.infer<typeof UpdateRagConfigRequestSchema>;
export type AddChunkingStrategyRequest = z.infer<typeof AddChunkingStrategyRequestSchema>;
export type RagChunkingStrategy = z.infer<typeof RagChunkingStrategySchema>;
export type UpdateChunkingStrategyRequest = z.infer<typeof UpdateChunkingStrategyRequestSchema>;
export type HttpValidationError = z.infer<typeof HttpValidationErrorSchema>;
export type DatasourceWebConfig = z.infer<typeof DatasourceWebConfigSchema>;
export type GetActivitiesResponse = z.infer<typeof GetActivitiesResponseSchema>;
export type ListContentResponse = z.infer<typeof ListContentResponseSchema>;
export type DataElementFilterRequest = z.infer<typeof DataElementFilterRequestSchema>;
export type DatabaseConfigInput = z.infer<typeof DatabaseConfigInputSchema>;
export type DatabaseConfigOutput = z.infer<typeof DatabaseConfigOutputSchema>;
export type GetBlueprintsResponse = z.infer<typeof GetBlueprintsResponseSchema>;
export type BlueprintInstance = z.infer<typeof BlueprintInstanceSchema>;
export type GetEventsResponse = z.infer<typeof GetEventsResponseSchema>;
export type ChatMessageResponse = z.infer<typeof ChatMessageResponseSchema>;
export type AddDatasourceRequest = z.infer<typeof AddDatasourceRequestSchema>;
export type Datasource = z.infer<typeof DatasourceSchema>;
export type UpdateDatasourceRequest = z.infer<typeof UpdateDatasourceRequestSchema>;
export type AddTagConfigRequest = z.infer<typeof AddTagConfigRequestSchema>;
export type UpdateTagConfigRequest = z.infer<typeof UpdateTagConfigRequestSchema>;
export type TagConfig = z.infer<typeof TagConfigSchema>;
export type GetBlueprintInstancesResponse = z.infer<typeof GetBlueprintInstancesResponseSchema>;
