/**
 * Generic Zod → JSON Schema conversion for smart-param `accept: schema` fields.
 *
 * When a method accepts a schema parameter, callers may pass either a plain
 * JSON-Schema object or a Zod schema. This converts the latter to JSON Schema
 * so the wire payload is always plain JSON Schema.
 *
 * Generated by Forge SDK Generator.
 */

import { z } from "zod";
import { zodObjectToJsonSchema } from "./artifacts.js";

/**
 * Convert a Zod object schema into a plain JSON Schema object.
 *
 * @param schema A Zod object schema (`z.object({ ... })`).
 * @returns A JSON Schema representation of the schema.
 */
export function zodToJsonSchema(schema: z.ZodType): Record<string, unknown> {
  if (schema instanceof z.ZodObject) {
    return zodObjectToJsonSchema(schema);
  }
  throw new TypeError(
    "zodToJsonSchema expects a Zod object schema (z.object({ ... }))."
  );
}
