/**
 * System Agent Helpers
 *
 * Convenience functions for system-agent one-liners that accept
 * Zod schemas or artifact schema IDs and handle conversion automatically.
 *
 * Generated by Forge SDK Generator.
 */

import { z } from "zod";

// ---------------------------------------------------------------------------
// Zod type introspection helpers (shared with artifacts.ts)
// ---------------------------------------------------------------------------

function unwrapZodType(zodType: z.ZodTypeAny): z.ZodTypeAny {
  if (zodType instanceof z.ZodOptional || zodType instanceof z.ZodNullable) {
    return unwrapZodType((zodType as any)._def.innerType);
  }
  if (zodType instanceof z.ZodDefault) {
    return unwrapZodType((zodType as any)._def.innerType);
  }
  return zodType;
}

function isOptionalType(zodType: z.ZodTypeAny): boolean {
  if (zodType instanceof z.ZodOptional || zodType instanceof z.ZodNullable) {
    return true;
  }
  if (zodType instanceof z.ZodDefault) {
    return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// JSON Schema generation from Zod
// ---------------------------------------------------------------------------

function zodTypeToJsonSchema(zodType: z.ZodTypeAny): Record<string, unknown> {
  const inner = unwrapZodType(zodType);

  if (inner instanceof z.ZodString) {
    return { type: "string" };
  }
  if (inner instanceof z.ZodNumber) {
    const checks = (inner as any)._def.checks as
      | Array<{ kind: string }>
      | undefined;
    if (checks?.some((c) => c.kind === "int")) {
      return { type: "integer" };
    }
    return { type: "number" };
  }
  if (inner instanceof z.ZodBoolean) {
    return { type: "boolean" };
  }
  if (inner instanceof z.ZodDate) {
    return { type: "string", format: "date-time" };
  }
  if (inner instanceof z.ZodEnum) {
    const values = (inner as any)._def.values as string[];
    return { type: "string", enum: values };
  }
  if (inner instanceof z.ZodArray) {
    const itemType = (inner as any)._def.type as z.ZodTypeAny;
    return { type: "array", items: zodTypeToJsonSchema(itemType) };
  }
  if (inner instanceof z.ZodObject) {
    return zodObjectToJsonSchema(inner);
  }

  return { type: "string" };
}

function zodObjectToJsonSchema(
  schema: z.ZodObject<any>
): Record<string, unknown> {
  const shape = schema.shape as Record<string, z.ZodTypeAny>;
  const properties: Record<string, unknown> = {};
  const requiredFields: string[] = [];

  for (const [name, zodType] of Object.entries(shape)) {
    const jsonType = zodTypeToJsonSchema(zodType);
    if (zodType.description) {
      (jsonType as any).description = zodType.description;
    }
    properties[name] = jsonType;

    if (!isOptionalType(zodType)) {
      requiredFields.push(name);
    }
  }

  const result: Record<string, unknown> = {
    type: "object",
    properties,
  };

  if (schema.description) {
    result.title = schema.description;
  }

  if (requiredFields.length > 0) {
    result.required = requiredFields;
  }

  return result;
}

// ---------------------------------------------------------------------------
// Schema resolution
// ---------------------------------------------------------------------------

/**
 * Resolve a schema argument to a value suitable for artifactSchema.
 *
 * Accepts:
 *   - A Zod object schema → converted to JSON Schema
 *   - A plain object → passed through as a raw JSON Schema
 *   - A string artifact schema ID → passed through as-is
 */
function resolveSchema(
  schema: string | Record<string, unknown> | z.ZodObject<any>
): string | Record<string, unknown> {
  if (typeof schema === "string") {
    return schema;
  }
  if (schema instanceof z.ZodObject) {
    return zodObjectToJsonSchema(schema);
  }
  return schema;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

interface TransformOptions {
  file: string;
  schema: string | Record<string, unknown> | z.ZodObject<any>;
  model?: string;
  prompt?: string;
  promptId?: string;
  timeoutSeconds?: number;
}

/**
 * Transform a document using a Zod schema, JSON Schema object, or artifact schema ID.
 *
 * Calls the sync `client.documents.transform()` endpoint. When a Zod
 * schema is provided, it is automatically converted to JSON Schema for the
 * artifactSchema field. A plain object is passed through as a raw JSON Schema.
 * A string is passed through as an artifact schema ID.
 *
 * @example
 * ```typescript
 * import { z } from "zod";
 * import { MeibelClient, transformDocument } from "meibel";
 *
 * // With a Zod schema:
 * const InvoiceOutput = z.object({
 *   vendorName: z.string().describe("Name of the vendor"),
 *   totalAmount: z.number().describe("Invoice total"),
 * });
 *
 * const result = await transformDocument(client, {
 *   file: "invoice.pdf",
 *   schema: InvoiceOutput,
 * });
 *
 * // With an artifact schema ID:
 * const result2 = await transformDocument(client, {
 *   file: "invoice.pdf",
 *   schema: "artifact-schema-id-123",
 * });
 * ```
 */
export function transformDocument(
  client: any,
  options: TransformOptions
): Promise<any> {
  return client.documents.transform({
    file: options.file,
    artifactSchema: resolveSchema(options.schema),
    model: options.model,
    prompt: options.prompt,
    promptId: options.promptId,
    timeoutSeconds: options.timeoutSeconds,
  });
}

/**
 * Submit an async document transform using a Zod schema, JSON Schema object, or artifact schema ID.
 *
 * Returns immediately with an executionId. Poll for completion via
 * `client.sessions.get(executionId)`.
 *
 * @example
 * ```typescript
 * const job = await submitDocumentTransform(client, {
 *   file: "invoice.pdf",
 *   schema: InvoiceOutput,
 * });
 * // ... do other work ...
 * const session = await client.sessions.get(job.executionId);
 * ```
 */
export function submitDocumentTransform(
  client: any,
  options: Omit<TransformOptions, "timeoutSeconds">
): Promise<any> {
  return client.documents.submitTransform({
    file: options.file,
    artifactSchema: resolveSchema(options.schema),
    model: options.model,
    prompt: options.prompt,
    promptId: options.promptId,
  });
}
