/**
 * Streaming Multipart Upload Module
 *
 * Provides zero-copy streaming multipart/form-data encoding.
 * Files are streamed in chunks — never fully buffered in memory.
 *
 * Generated by Forge SDK Generator.
 */

export interface UploadFile {
  fieldName: string;
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | File | ArrayBufferView;
}

export function createMultipartStream(
  files: UploadFile[],
  formFields?: Record<string, string>,
  boundary?: string,
): { body: ReadableStream<Uint8Array>; contentType: string } {
  const b =
    boundary ??
    `----FormBoundary${Math.random().toString(36).slice(2)}${Date.now().toString(36)}`;
  const encoder = new TextEncoder();

  const body = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        // Form fields first
        if (formFields) {
          for (const [key, value] of Object.entries(formFields)) {
            controller.enqueue(
              encoder.encode(
                `--${b}\r\nContent-Disposition: form-data; name="${key}"\r\n\r\n${value}\r\n`,
              ),
            );
          }
        }

        // File parts
        for (const file of files) {
          controller.enqueue(
            encoder.encode(
              `--${b}\r\nContent-Disposition: form-data; name="${file.fieldName}"; filename="${file.fileName}"\r\nContent-Type: application/octet-stream\r\n\r\n`,
            ),
          );

          if (file.content instanceof ReadableStream) {
            const reader = file.content.getReader();
            for (;;) {
              const { done, value } = await reader.read();
              if (done) break;
              controller.enqueue(value);
            }
          } else if (file.content instanceof Blob) {
            const reader = file.content.stream().getReader();
            for (;;) {
              const { done, value } = await reader.read();
              if (done) break;
              controller.enqueue(value);
            }
          } else {
            // ArrayBufferView (Buffer, Uint8Array, etc.)
            controller.enqueue(
              new Uint8Array(file.content.buffer, file.content.byteOffset, file.content.byteLength),
            );
          }

          controller.enqueue(encoder.encode('\r\n'));
        }

        controller.enqueue(encoder.encode(`--${b}--\r\n`));
        controller.close();
      } catch (err) {
        controller.error(err);
      }
    },
  });

  return { body, contentType: `multipart/form-data; boundary=${b}` };
}
